import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile, mkdtemp, rm } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { rolldown } from 'rolldown'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { CAD_VIEW_COLORS, cadCanvasActive, cadCameraPreset, cadFallbackUrl, cadPickTolerance, cadPlaneForFace, createCadTopologyScene, createCadViewportTopology, fitCadCamera, nextCadSelection, validateCadViewportGeometry } from './cadModelViewport.js'

// Generated by the real OCCT preview exporter. The associated STEP was read
// back as one valid solid; no face or edge in this fixture is a center marker.
const fixture = JSON.parse(await readFile(new URL('./fixtures/cadViewportBoxBore.json', import.meta.url), 'utf8'))
const ray = (origin, direction = [0, 0, -1]) => new THREE.Raycaster(new THREE.Vector3(...origin), new THREE.Vector3(...direction).normalize())
const approximately = (actual, expected, tolerance = 1e-5) => assert.ok(Math.abs(actual - expected) < tolerance, `${actual} should equal ${expected}`)

test('actual OCCT GLB vertices and triangles exactly match the viewport tessellation and STEP bounds', async () => {
  const bytes = await readFile(new URL('./fixtures/cadViewportBoxBore.glb', import.meta.url))
  assert.equal(createHash('sha256').update(bytes).digest('hex'), fixture.provenance.glbSha256)
  assert.equal(fixture.provenance.stepValid, true)
  approximately(fixture.provenance.stepVolumeMm3, 20 * 16 * 10 - Math.PI * 3 ** 2 * 10)
  const gltf = await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), '')
  const meshes = []; gltf.scene.traverse(node => { if (node.isMesh) meshes.push(node) })
  assert.equal(meshes.length, 1)
  const actual = meshes[0].geometry
  assert.deepEqual(Array.from(actual.index.array), fixture.result.mesh.indices)
  const expected = new Float32Array(fixture.result.mesh.positions)
  assert.deepEqual(actual.attributes.position.array, expected)
  const topology = createCadTopologyScene(fixture.result)
  try {
    assert.deepEqual(topology.bounds.min.toArray(), [0, 0, 0]); assert.deepEqual(topology.bounds.max.toArray(), [20, 16, 10])
    assert.equal(topology.mesh.geometry.attributes.position.count / 3, fixture.result.counts.triangles)
    assert.equal(topology.edges.length, fixture.result.counts.edges)
  } finally { topology.dispose(); actual.dispose(); meshes[0].material.dispose() }
})

test('each actual OCCT triangle resolves to its source face with the exact versioned selector', () => {
  const topology = createCadTopologyScene(fixture.result), mesh = fixture.result.mesh, faces = new Set()
  try {
    for (let index = 0; index < mesh.faceIds.length; index++) {
      const vertices = mesh.indices.slice(index * 3, index * 3 + 3).map(vertex => new THREE.Vector3(...mesh.positions.slice(vertex * 3, vertex * 3 + 3)))
      const center = vertices[0].clone().add(vertices[1]).add(vertices[2]).divideScalar(3)
      const normal = vertices[1].clone().sub(vertices[0]).cross(vertices[2].clone().sub(vertices[0])).normalize()
      const hit = topology.pick(new THREE.Raycaster(center.clone().addScaledVector(normal, 1e-4), normal.negate()), 'face')
      assert.equal(hit?.id, mesh.faceIds[index], `triangle ${index}`)
      assert.deepEqual(hit.selector, fixture.result.faces[hit.index].selector)
      approximately(new THREE.Vector3(...hit.worldPoint).distanceTo(center), 0)
      faces.add(hit.id)
    }
    assert.equal(faces.size, 7)
  } finally { topology.dispose() }
})

test('faces are picked at their surfaces, holes stay empty, and curved faces cannot become sketch planes', () => {
  const topology = createCadTopologyScene(fixture.result)
  try {
    const surface = topology.pick(ray([2, 3, 50]), 'face')
    assert.equal(surface.id, 'face:2'); assert.deepEqual(surface.worldPoint, [2, 3, 10])
    assert.notDeepEqual(surface.worldPoint, fixture.result.faces[2].origin)
    assert.deepEqual(surface.plane.origin, [10, 8, 10]); assert.deepEqual(surface.plane.normal, [0, 0, 1])
    assert.equal(topology.pick(ray([10, 8, 50]), 'face'), null, 'A ray through the bore must not hit the planar face bounding box')
    const bore = topology.pick(ray([10, 8, 5], [1, 0, 0]), 'face')
    assert.equal(bore.surfaceType, 'CYLINDER'); assert.equal(bore.id, 'face:6'); assert.equal(bore.plane, null)
    approximately(bore.worldPoint[0], 13)
    assert.equal(topology.pick(ray([100, 100, 50]), 'all'), null)
    assert.equal(topology.pick(ray([2, 3, 50]), 'none'), null)
  } finally { topology.dispose() }
})

test('straight and circular edge hits follow actual sampled curves and reject occluded back edges', () => {
  const topology = createCadTopologyScene(fixture.result)
  try {
    const line = topology.pick(ray([-20, -20, 3], [1, 1, 0]), 'edge', 0.01)
    assert.equal(line.id, 'edge:0'); assert.deepEqual(line.worldPoint, [0, 0, 3])
    const circle = fixture.result.edges[9], midpoint = [0, 1, 2].map(axis => (circle.points[3 + axis] + circle.points[6 + axis]) / 2)
    const circular = topology.pick(ray([midpoint[0], midpoint[1], 50]), 'edge', 0.01)
    assert.equal(circular.id, circle.id); assert.deepEqual(circular.selector, circle.selector)
    approximately(circular.worldPoint[2], 10)
    assert.equal(topology.pick(ray([2, 3, 50]), 'edge', 0.01), null)
    const front = topology.pick(ray([-20, -20, 3], [1, 1, 0]), 'all', 0.01)
    assert.equal(front.id, 'edge:0', 'Back corner edge:11 is hidden by the front surface')
  } finally { topology.dispose() }
})

test('transaction results display their new hole while selectionGeometry continues to pick the original input face', () => {
  const viewport = createCadViewportTopology(fixture.result, fixture.input)
  try {
    assert.equal(viewport.separate, true)
    assert.equal(viewport.display.pick(ray([10, 8, 50]), 'face'), null)
    const hit = viewport.pick(ray([10, 8, 50]), 'face')
    assert.ok(hit); assert.equal(hit.selector.sourceFeatureId, 'block')
    assert.equal(hit.selector.geometryVersion, fixture.input.geometryVersion)
    assert.notEqual(hit.selector.geometryVersion, fixture.result.geometryVersion)
    assert.deepEqual(hit.worldPoint, [10, 8, 10])
    assert.equal(viewport.picking.mesh.visible, false, 'The input must not cover the displayed transaction result')
    viewport.highlight([hit])
    const overlays = []; viewport.picking.group.traverse(node => { if (node.isMesh && node !== viewport.picking.mesh) overlays.push(node) })
    assert.equal(overlays.length, 1)
    assert.equal(overlays[0].material.transparent, true); assert.equal(overlays[0].material.depthTest, false)
    const positions = overlays[0].geometry.attributes.position
    for (let i = 0; i < positions.count; i++) approximately(positions.getZ(i), 10)
    viewport.highlight([{ ...hit, selector: { ...hit.selector, geometryVersion: fixture.result.geometryVersion } }])
    assert.equal(viewport.picking.group.children.at(-1).children.length, 0, 'A stale same-index selector must not highlight the replacement geometry')
    viewport.setAppearance('wireframe'); assert.equal(viewport.display.mesh.visible, false)
    viewport.setAppearance('shaded'); assert.equal(viewport.display.mesh.visible, true)
  } finally { viewport.dispose() }
  const same = createCadViewportTopology(fixture.result, fixture.result)
  try { assert.equal(same.display, same.picking); assert.equal(same.separate, false) } finally { same.dispose() }
})

test('selection and hover color whole real faces and make selected curves visibly wider', () => {
  const topology = createCadTopologyScene(fixture.result)
  try {
    const face = topology.pick(ray([2, 3, 50]), 'face'), edge = topology.pick(ray([-20, -20, 3], [1, 1, 0]), 'edge', 0.01)
    topology.setResolution(1200, 800); topology.highlight([face], edge)
    const color = new THREE.Color(CAD_VIEW_COLORS.selected), attribute = topology.mesh.geometry.attributes.color
    for (let i = 0; i < fixture.result.mesh.faceIds.length; i++) if (fixture.result.mesh.faceIds[i] === face.id) {
      for (let vertex = i * 3; vertex < i * 3 + 3; vertex++) { approximately(attribute.getX(vertex), color.r); approximately(attribute.getY(vertex), color.g); approximately(attribute.getZ(vertex), color.b) }
    }
    const emphasis = []; topology.group.traverse(node => { if (node.isLine2) emphasis.push(node) })
    assert.equal(emphasis.length, 1); assert.ok(emphasis[0].material.linewidth > 2)
    assert.deepEqual(emphasis[0].material.resolution.toArray(), [1200, 800])
    topology.setAppearance('wireframe')
    assert.equal(topology.mesh.visible, false)
    assert.ok(topology.group.children.at(-1).children.some(node => node.isMesh), 'A selected face stays highlighted even in wireframe mode')
    topology.setAppearance('shaded'); assert.equal(topology.mesh.visible, true)
    topology.highlight([], null); assert.equal(topology.group.children.at(-1).children.length, 0)
  } finally { topology.dispose() }
})

test('single selection, Ctrl multi-selection and blank cancellation preserve selectors without changing source data', () => {
  const a = { kind: 'face', ...fixture.input.faces[0] }, b = { kind: 'edge', ...fixture.input.edges[0] }
  const first = nextCadSelection([], a), multi = nextCadSelection(first, b, true)
  assert.deepEqual(first, [a]); assert.deepEqual(multi, [a, b])
  assert.deepEqual(nextCadSelection(multi, a, true), [b]); assert.deepEqual(nextCadSelection(multi, b), [b])
  assert.deepEqual(nextCadSelection(multi, null, true), []); assert.deepEqual(first, [a])
})

test('standard views frame all actual geometry in desktop and mobile aspect ratios', () => {
  const bounds = new THREE.Box3(new THREE.Vector3(0, 0, 0), new THREE.Vector3(20, 16, 10))
  for (const view of ['iso', 'top', 'front', 'right']) for (const aspect of [0.5, 1, 2.5]) {
    const camera = new THREE.OrthographicCamera(), target = fitCadCamera(camera, bounds, { view, aspect })
    assert.deepEqual(target.toArray(), [10, 8, 5])
    assert.ok(camera.getWorldDirection(new THREE.Vector3()).dot(new THREE.Vector3(...cadCameraPreset(view).direction).normalize()) < -0.999)
    for (const x of [0, 20]) for (const y of [0, 16]) for (const z of [0, 10]) {
      const point = new THREE.Vector3(x, y, z).project(camera)
      assert.ok(Math.abs(point.x) < 1 && Math.abs(point.y) < 1 && Math.abs(point.z) < 1, `${view} ${aspect}`)
    }
    const oldTolerance = cadPickTolerance(camera, 800); camera.zoom = 2
    approximately(cadPickTolerance(camera, 800), oldTolerance / 2)
  }
  assert.equal(cadCanvasActive({ active: false, hidden: false, width: 100, height: 100 }), false)
  assert.equal(cadCanvasActive({ active: true, hidden: false, width: 0, height: 100 }), false)
  assert.equal(cadCanvasActive({ active: true, hidden: true, width: 100, height: 100 }), false)
  assert.equal(cadCanvasActive({ active: true, hidden: false, width: 100, height: 100 }), true)
})

test('invalid geometry mappings and mismatched signed topology cannot silently become pickable', () => {
  for (const mutate of [value => { value.valid = false }, value => { value.mesh.faceIds.pop() }, value => { value.mesh.indices[0] = 999999 }, value => { value.mesh.positions[0] = NaN }, value => { value.mesh.normals[0] = Infinity }, value => { value.mesh.faceIds[0] = 'face:999' }, value => { value.faces[0].selector.geometryVersion = '0'.repeat(64) }, value => { value.edges[0].selector.signature = 'missing' }, value => { value.faces[0].normal = [0, 0, 0] }, value => { value.faces[0].xAxis = value.faces[0].normal }]) {
    const payload = structuredClone(fixture.result); mutate(payload)
    assert.throws(() => validateCadViewportGeometry(payload), /实体预览数据不完整/)
  }
  assert.equal(cadPlaneForFace({ planar: true, center: [1, 2, 3] }), null)
  assert.equal(cadPlaneForFace(fixture.result.faces[6]), null)
})

test('fallback GLB addresses never forward credentials to another host or unsafe protocol', () => {
  const base = 'https://cad.example/api/v1'
  assert.equal(cadFallbackUrl('/api/cad/features/previews/a/artifacts/glb', base), 'https://cad.example/api/cad/features/previews/a/artifacts/glb')
  assert.equal(cadFallbackUrl('blob:https://cad.example/own-object', base), 'blob:https://cad.example/own-object')
  for (const value of [undefined, '', 'https://other.example/model.glb', 'blob:https://other.example/foreign', 'javascript:alert(1)', 'file:///tmp/model.glb', 'https://u:p@cad.example/model.glb']) assert.throws(() => cadFallbackUrl(value, base), /预览地址/)
})

let temporary, Viewport
async function loadViewport() {
  if (Viewport) return Viewport
  temporary = await mkdtemp(resolve('node_modules/.cad-viewport-tests-'))
  const bundle = await rolldown({ input: resolve('src/CadModelViewport.jsx'), external: source => source === 'react' || source.startsWith('react/') || source === 'three' || source.startsWith('three/'), transform: { jsx: { runtime: 'automatic' } }, plugins: [{ name: 'ignore-viewport-css', load(id) { if (id.endsWith('.css')) return { code: '', moduleType: 'js' } } }] })
  await bundle.write({ dir: temporary, format: 'esm' }); await bundle.close()
  Viewport = (await import(pathToFileURL(resolve(temporary, 'CadModelViewport.js')).href)).default
  return Viewport
}
test.after(async () => { if (temporary) await rm(temporary, { recursive: true, force: true }) })

test('viewport exposes CAD controls and offers sketch creation only for a current selected planar face', async () => {
  const Viewport = await loadViewport()
  const surface = { ...fixture.result.faces[2], kind: 'face' }
  const markup = renderToStaticMarkup(React.createElement(Viewport, { geometry: fixture.result, selection: [surface], onPlaneSelect() {} }))
  for (const label of ['上视图', '前视图', '右视图', '等轴测', '拖动旋转模型', '拖动平移模型', '放大模型', '缩小模型', '适合窗口', '在所选平面创建草图']) assert.ok(markup.includes(label), label)
  const curved = renderToStaticMarkup(React.createElement(Viewport, { geometry: fixture.result, selection: [{ ...fixture.result.faces[6], kind: 'face' }], onPlaneSelect() {} }))
  assert.ok(!curved.includes('在所选平面创建草图'))
  const stale = renderToStaticMarkup(React.createElement(Viewport, { geometry: fixture.result, selection: [{ ...surface, selector: { ...surface.selector, geometryVersion: fixture.input.geometryVersion } }], onPlaneSelect() {} }))
  assert.ok(!stale.includes('在所选平面创建草图'))
  const fallback = renderToStaticMarkup(React.createElement(Viewport, { fallback: '/model.glb' }))
  assert.match(fallback, /此预览仅供查看/); assert.ok(!fallback.includes('在所选平面创建草图'))
})
