const param=(label,value)=>({label,value,source:{type:'user',text:'教学案例的已知设计尺寸'}})
const plan=(name,parameters,features,result=features.at(-1).id)=>({version:'cad-plan-v1',name,units:'mm',parameters,features,result,notes:['教学案例的尺寸属于本案例设计条件，可在特征编辑器内调整。']})
export const MECHANICAL_CASES=[
{id:'spacer',name:'带通孔隔套',level:'入门',summary:'圆柱与布尔切除，修改内外径。',steps:['外圆柱定义外径和长度','内圆柱贯穿零件','布尔切除形成通孔','核对体积和孔径，导出 STEP'],plan:plan('带通孔隔套',{outer: param('外径',40),inner:param('内径',20),height:param('长度',30)},[{id:'outer',op:'cylinder',radius:'outer/2',height:'height'},{id:'bore',op:'cylinder',radius:'inner/2',height:'height+2',origin:[0,0,-1]},{id:'part',op:'cut',inputs:['outer','bore']}])},
{id:'flange',name:'四孔法兰',level:'基础',summary:'环形阵列生成螺栓孔。',steps:['建立带中心孔的法兰','设置螺栓圆直径和孔径','圆周阵列生成四个孔刀具','切除孔阵列并核对孔位'],plan:plan('四孔法兰',{diameter:param('法兰外径',80),thickness:param('厚度',12),bore:param('中心孔径',24),pcd:param('螺栓圆直径',58),hole:param('安装孔径',8)},[{id:'blank',op:'cylinder',radius:'diameter/2',height:'thickness'},{id:'bore',op:'cylinder',radius:'bore/2',height:'thickness+2',origin:[0,0,-1]},{id:'ring',op:'cut',inputs:['blank','bore']},{id:'hole',op:'cylinder',radius:'hole/2',height:'thickness+2',origin:['pcd/2',0,-1]},{id:'holes',op:'circular_pattern',input:'hole',count:4,axisStart:[0,0,0],axisEnd:[0,0,1],angle:360},{id:'part',op:'cut',inputs:['ring','holes']}])},
{id:'shaft',name:'三级阶梯轴',level:'基础',summary:'多个同轴实体与表达式关联。',steps:['定义每级直径与长度','用前序长度表达式确定台阶位置','布尔合并形成一个实体','调整任意长度，检查端面位置'],plan:plan('三级阶梯轴',{d1:param('大端直径',40),d2:param('中段直径',28),d3:param('小端直径',18),l1:param('大端长度',15),l2:param('中段长度',40),l3:param('小端长度',20)},[{id:'a',op:'cylinder',radius:'d1/2',height:'l1'},{id:'b',op:'cylinder',radius:'d2/2',height:'l2',origin:[0,0,'l1']},{id:'c',op:'cylinder',radius:'d3/2',height:'l3',origin:[0,0,'l1+l2']},{id:'part',op:'union',inputs:['a','b','c']}])},
{id:'bracket',name:'L 形支架',level:'基础',summary:'L 形草图拉伸与贯穿安装孔。',steps:['在 XZ 平面绘制 L 形截面','按指定宽度拉伸','建立贯穿安装孔','检查截面和安装面'],plan:plan('L形支架',{length:param('底边长度',70),height:param('立边高度',50),wall:param('壁厚',8),width:param('宽度',35),hole:param('安装孔径',10)},[{id:'body',op:'profile_extrude',plane:'XZ',origin:[0,'width',0],start:[0,0],segments:[{type:'line',to:['length',0]},{type:'line',to:['length','wall']},{type:'line',to:['wall','wall']},{type:'line',to:['wall','height']},{type:'line',to:[0,'height']}],distance:'width'},{id:'hole',op:'cylinder',radius:'hole/2',height:'wall+2',origin:['length*0.7','width/2',-1]},{id:'part',op:'cut',inputs:['body','hole']}])},
{id:'gear',name:'渐开线直齿轮',level:'专用',summary:'模数、齿数、压力角、齿宽及中心孔。',steps:['输入模数与齿数','设置压力角、变位和齿宽','生成实际渐开线实体','用节圆/齿顶圆尺寸核对'],plan:plan('渐开线直齿轮',{module:param('模数',2),teeth:param('齿数',24),pressure:param('压力角',20),width:param('齿宽',15),bore:param('中心孔径',12)},[{id:'gear',op:'gear',module:'module',teeth:'teeth',pressureAngle:'pressure',width:'width',boreDiameter:'bore',profileShift:0,backlash:0}])},
{id:'spring',name:'等螺距弹簧',level:'专用',summary:'线径、中径、螺距与圈数。',steps:['输入钢丝直径与弹簧中径','设置螺距和有效圈数','扫掠生成连续实体','检查自由高度和螺旋方向'],plan:plan('等螺距弹簧',{mean:param('弹簧中径',24),wire:param('线径',3),pitch:param('螺距',8),turns:param('圈数',5)},[{id:'spring',op:'spring',meanDiameter:'mean',wireDiameter:'wire',pitch:'pitch',turns:'turns',lefthand:false}])},
{id:'shell',name:'开口壳体',level:'进阶',summary:'方体移除顶面并向内抽壳。',steps:['建立外包络方体','移除顶面并向内抽壳','验证剩余壁厚','以截面检查内部空腔'],plan:plan('开口壳体',{length:param('长度',80),width:param('宽度',50),height:param('高度',30),wall:param('壁厚',3)},[{id:'blank',op:'box',size:['length','width','height']},{id:'part',op:'shell',input:'blank',thickness:'-wall',faces:['maxZ']}])},
{id:'chamfer',name:'倒角垫块',level:'入门',summary:'倒角特征可直接编辑和抑制。',steps:['建立方体基座','选择所有边进行倒角','修改倒角距离','抑制倒角观察实体变化'],plan:plan('倒角垫块',{length:param('长度',40),width:param('宽度',30),height:param('高度',15),chamfer:param('倒角长度',1)},[{id:'blank',op:'box',size:['length','width','height']},{id:'part',op:'chamfer',input:'blank',length:'chamfer',edges:'all'}])},
{id:'sweep',name:'折线管状实心件',level:'进阶',summary:'圆截面沿折线路径扫掠。',steps:['设置截面半径','编辑路径坐标','生成斜接连续扫掠实体','检查路径转折和体积'],plan:plan('折线路径扫掠',{radius:param('圆截面半径',3)},[{id:'sweep',op:'sweep',path:[[0,0,0],[0,0,30],[20,0,50],[45,0,50]],radius:'radius'}])},
{id:'loft',name:'多截面放样体',level:'进阶',summary:'圆截面由小到大再收缩。',steps:['设置三个截面位置和半径','选择平滑或直纹放样','构建封闭实体','用截面和包络核对'],plan:plan('多截面放样',{r1:param('底面半径',10),r2:param('中间半径',20),r3:param('顶面半径',8),height:param('总高度',50)},[{id:'loft',op:'loft',sections:[{origin:[0,0,0],radius:'r1'},{origin:[0,0,'height/2'],radius:'r2'},{origin:[0,0,'height'],radius:'r3'}],ruled:false}])},
{id:'linear',name:'五孔安装板',level:'基础',summary:'线性阵列与间距参数。',steps:['按孔间距派生板长','建立第一个孔刀具','线性阵列五个刀具','布尔切除并核对所有孔'],plan:plan('五孔安装板',{pitch:param('孔距',20),hole:param('孔径',6),width:param('板宽',20),thickness:param('板厚',5)},[{id:'plate',op:'box',size:['pitch*6','width','thickness']},{id:'tool',op:'cylinder',radius:'hole/2',height:'thickness+2',origin:['pitch','width/2',-1]},{id:'holes',op:'linear_pattern',input:'tool',count:5,vector:['pitch',0,0]},{id:'part',op:'cut',inputs:['plate','holes']}])},
{id:'revolve',name:'旋转轴套',level:'进阶',summary:'二维封闭轮廓绕轴旋转。',steps:['绘制半截面，保留内孔','指定旋转轴与角度','旋转生成台阶轴套','修改轮廓尺寸并重建'],plan:plan('旋转轴套',{inner:param('内孔半径',8),outer:param('外圆半径',18),flange:param('法兰半径',25),height:param('总长',35),lip:param('法兰厚度',8)},[{id:'part',op:'profile_revolve',plane:'XZ',start:['inner',0],segments:[{type:'line',to:['flange',0]},{type:'line',to:['flange','lip']},{type:'line',to:['outer','lip']},{type:'line',to:['outer','height']},{type:'line',to:['inner','height']}],axisStart:[0,0],axisEnd:[0,1],angle:360}])},
]
export const CAD_LESSONS=[
 {id:'first',title:'第一次从文字生成零件',steps:['在 3D 建模页描述用途、尺寸和要保留的孔槽。','发送后等待真实实体构建，查看尺寸与视图。','补充未确定信息，继续对话修正。','核对当前模型并确认后下载 STEP。'],mode:'3D 建模'},
 {id:'native',title:'修改已有 DWG / DXF',steps:['打开原生二维，导入图纸并查看实体及图层。','点击图元，Shift 可多选；修改属性或用变换工具。','添加尺寸、公差、几何约束和参数公式。','使用整图预览核对，导出 DXF / PDF 或尺寸 Excel。'],mode:'原生二维'},
 {id:'photo',title:'把零件照片变成 CAD',steps:['上传主视与补充照片。','在主照片点选已知尺寸的两端。','补充厚度、孔深和背面结构。','进入会话生成并继续核对。'],mode:'照片建模'},
 {id:'assembly',title:'从真实零件到装配和工程图',steps:['打开工程设计，上传 STEP 或导入当前已确认模型。','添加零件实例和变换，指定基本配合。','求解后检查配合残差与实体干涉，导出 STEP / BOM。','选择投影、剖面和布局，加尺寸后导出 DXF / PDF。'],mode:'工程设计'},
]
