import { createClientId } from './clientId.js'
import { useEffect, useRef, useState } from 'react'
import { nativeDrawingRequest as request, saveNativeBlob } from './nativeDrawingClient.js'
import { CONSTRAINT_TYPES, PROFESSIONAL_SYMBOLS, drawingBounds, evaluateFormula, professionalSymbol, snapPoint, solveConstraints, transformEntity } from './nativeDrawingModel.js'
import { nativeDimensionDraft, nativeLayouts, validNativeLayout, visibleNativeEntities, nativePolylineText, parseNativePolylineText, nativePropertyDirty, nativeVisibleRenderEntities, nativeDialogKey } from './nativeDrawingDraft.js'
import NativeParametricLibrary from './NativeParametricLibrary.jsx'
import './native-drawing.css'
import './native-cad-shell.css'
import JoyNiuBrand from './JoyNiuBrand.jsx'
import {NativeCadIcon, nativeCadRibbon} from './NativeCadRibbon.jsx'
import {cadCoordinate, cadBoxSelection, cadTransformValues, cadMirror, cadCornerOperations, cadTrimOperation} from './nativeCadInteraction.js'
const TOOLS={select:'选择',line:'直线 L',rectangle:'矩形 REC',circle:'圆 C',arc:'圆弧 A',polyline:'多段线 PL',text:'文字 T',dimension:'标注 D',bubble:'气泡 B',polygon:'正多边形',ellipse:'椭圆'}
const TOOL_GROUPS={select:{label:'选择',tools:['select'],initial:'select'},draw:{label:'绘制',tools:['line','rectangle','circle','arc','polyline'],initial:'line'},annotate:{label:'标注',tools:['dimension','text','bubble'],initial:'dimension'},transform:{label:'变换',tools:[],initial:'select'}}
const TRANSFORMS={move:'移动',copy:'复制',rotate:'旋转',scale:'缩放',mirror:'镜像副本',array:'矩形阵列',polar:'环形阵列',offset:'偏移',trim:'裁剪直线'}
const COLORS=['#b6c0cc','#ef5c63','#e8c14c','#52c58c','#48bccf','#6194ff','#ba83ef','#d5dce5','#8694a8']
const colorOf=e=>e.trueColor!==undefined?`#${Number(e.trueColor).toString(16).padStart(6,'0')}`:COLORS[(e.color>0&&e.color<9?e.color:7)]
const displayEntity=(e,layers)=>{const l=layers.find(l=>l.name===e.layer);return {...e,color:e.color===256?(l?.color||7):e.color,linetype:(e.linetype||'BYLAYER').toUpperCase()==='BYLAYER'?(l?.linetype||'CONTINUOUS'):e.linetype,lineweight:e.lineweight===-1?(l?.lineweight??-1):e.lineweight}}
const fmt=n=>Number(Number(n||0).toFixed(4))
const entityChanges=e=>{const fields={LINE:['start','end'],CIRCLE:['center','radius'],ARC:['center','radius','startAngle','endAngle'],ELLIPSE:['center','majorAxis','ratio','startParam','endParam'],LWPOLYLINE:['points','closed'],TEXT:['position','height','rotation','text'],MTEXT:['position','height','rotation','text']}[e.type]||[];return Object.fromEntries(Object.entries(e).filter(([k])=>['layer','color','linetype','lineweight',...fields].includes(k)))}
function arcPath(e){const a=e.startAngle*Math.PI/180,b=e.endAngle*Math.PI/180,r=e.radius,[x,y]=e.center,s=[x+r*Math.cos(a),y+r*Math.sin(a)],t=[x+r*Math.cos(b),y+r*Math.sin(b)];return `M ${s[0]} ${s[1]} A ${r} ${r} 0 ${((e.endAngle-e.startAngle+360)%360)>180?1:0} 1 ${t[0]} ${t[1]}`}
function polylinePath(e){const p=e.points||[];if(!p.length)return '';let d=`M${p[0][0]} ${p[0][1]}`;for(let i=0;i<(e.closed?p.length:p.length-1);i++){const a=p[i],b=p[(i+1)%p.length],bulge=a[2]||0,chord=Math.hypot(b[0]-a[0],b[1]-a[1]);if(Math.abs(bulge)>1e-9&&chord>0){const r=chord*(1+bulge*bulge)/(4*Math.abs(bulge));d+=` A${r} ${r} 0 ${Math.abs(bulge)>1?1:0} ${bulge>0?1:0} ${b[0]} ${b[1]}`}else d+=` L${b[0]} ${b[1]}`}return d+(e.closed?' Z':'')}
function Entity({entity:e,selected,onSelect,scale=1}) {
  const props={stroke:selected?'#63d5ff':colorOf(e),strokeWidth:selected?2.4:Math.max(1.1,(e.lineweight>0?e.lineweight/100:0)*3.78),strokeDasharray:e.linetype==='DASHED'?'8 4':e.linetype==='CENTER'?'12 3 2 3':undefined,vectorEffect:'non-scaling-stroke',fill:e.filled?colorOf(e):'none',onPointerDown:onSelect,'data-entity':e.id,style:{cursor:'pointer'},className:'native-entity'}
  if(e.type==='LINE')return <line {...props} x1={e.start[0]} y1={e.start[1]} x2={e.end[0]} y2={e.end[1]}/>
  if(e.type==='CIRCLE')return <circle {...props} cx={e.center[0]} cy={e.center[1]} r={e.radius}/>
  if(e.type==='ELLIPSE'){const r=Math.hypot(...e.majorAxis.slice(0,2)),angle=Math.atan2(e.majorAxis[1],e.majorAxis[0])*180/Math.PI,a=e.startParam??0,b=e.endParam??Math.PI*2;if(Math.abs(b-a)<Math.PI*2-1e-8){const point=t=>[r*Math.cos(t),r*e.ratio*Math.sin(t)];return <path {...props} transform={`translate(${e.center[0]} ${e.center[1]}) rotate(${angle})`} d={`M${point(a).join(' ')} A${r} ${r*e.ratio} 0 ${((b-a+Math.PI*2)%(Math.PI*2))>Math.PI?1:0} 1 ${point(b).join(' ')}`}/>}return <ellipse {...props} cx={e.center[0]} cy={e.center[1]} rx={r} ry={r*e.ratio} transform={`rotate(${angle} ${e.center[0]} ${e.center[1]})`}/>}
  if(e.type==='ARC')return <path {...props} d={arcPath(e)}/>
  if(e.type==='LWPOLYLINE')return <path {...props} d={polylinePath(e)}/>
  if(e.type==='TEXT'||e.type==='MTEXT')return <text {...props} stroke="none" fill={props.stroke} transform={`translate(${e.position[0]},${e.position[1]}) rotate(${e.rotation||0}) scale(1,-1)`} fontSize={e.height||2.5} textAnchor={e.anchor||'start'} dominantBaseline={e.verticalAnchor==='middle'?'central':e.verticalAnchor==='top'?'hanging':'auto'}>{e.stackedTolerance?<><tspan>{e.stackedTolerance.base}</tspan><tspan dx={(e.height||2.5)*.15} dy={-(e.height||2.5)*.35} fontSize={(e.height||2.5)*.5}>{e.stackedTolerance.upper}</tspan><tspan dx={-(e.height||2.5)*.5*e.stackedTolerance.upper.length*.6} dy={(e.height||2.5)*.7} fontSize={(e.height||2.5)*.5}>{e.stackedTolerance.lower}</tspan></>:e.text}</text>
  if(e.type==='DIMENSION'){const p=e.points?.defpoint2||e.points?.defpoint||[0,0],q=e.points?.defpoint3||p,b=e.points?.defpoint||p;return <g {...props}><path d={`M${p[0]} ${p[1]} L${p[0]} ${b[1]} L${q[0]} ${b[1]} L${q[0]} ${q[1]}`}/><text stroke="none" fill={props.stroke} transform={`translate(${(p[0]+q[0])/2},${b[1]+3*scale}) scale(1,-1)`} fontSize={Math.max(e.style?.dimtxt||2.5,3*scale)} textAnchor="middle">{e.text&&e.text!=='<>'?e.text:fmt(e.value)}{e.toleranceEnabled?` +${e.toleranceUpper}/−${e.toleranceLower}`:''}</text></g>}
  if(e.position)return <g {...props}><circle cx={e.position[0]} cy={e.position[1]} r={4*scale}/><text fill={props.stroke} transform={`translate(${e.position[0]},${e.position[1]}) scale(1,-1)`} fontSize={4*scale}>{e.block||e.type}</text></g>
  return null
}
function Numeric({label,value,onChange,min,step='any'}){
  const [draft,setDraft]=useState(String(fmt(value)))
  // Undo/redo can change the source value while macOS leaves this input focused.
  // An unchanged numeric value does not rerun this effect, so "0." stays editable.
  useEffect(()=>{setDraft(String(fmt(value)))},[value])
  return <label>{label}<input type="number" step={step} min={min} value={draft} onBlur={()=>{if(draft.trim()===''||!Number.isFinite(Number(draft)))setDraft(String(fmt(value)))}} onChange={e=>{setDraft(e.target.value);if(e.target.value.trim()!==''&&Number.isFinite(Number(e.target.value)))onChange(Number(e.target.value))}}/></label>
}
export default function NativeDrawingWorkspace({token,accountKey=token,showToast=()=>{},active=true,onBack=()=>{},onLogin=()=>{},creditBalance}){
  const [ribbonPage,setRibbonPage]=useState('常用'),[inspectorOpen,setInspectorOpen]=useState(false),[fileOpen,setFileOpen]=useState(false),[gridVisible,setGridVisible]=useState(false),[snapEnabled,setSnapEnabled]=useState(true),[orthogonal,setOrthogonal]=useState(false),[polarTracking,setPolarTracking]=useState(false),[crosshair,setCrosshair]=useState(null),[box,setBox]=useState(null),[interaction,setInteraction]=useState(null),[commandLog,setCommandLog]=useState([]),[commandExpanded,setCommandExpanded]=useState(false),[activeLayout,setActiveLayout]=useState('Model'),[layoutPreview,setLayoutPreview]=useState(''),[layoutLoading,setLayoutLoading]=useState(false),[toolSettings,setToolSettings]=useState(false)
  const clipboard=useRef(null),boxStart=useRef(null),layoutEpoch=useRef(0),lastPoint=useRef([0,0]),layoutUrl=useRef('')
  const [toolGroup,setToolGroup]=useState('select'),[transformKind,setTransformKind]=useState('move')
  const [documents,setDocuments]=useState([]),[doc,setDoc]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tool,setTool]=useState('select'),[selection,setSelection]=useState([]),[view,setView]=useState({x:-100,y:-75,width:200,height:150}),[points,setPoints]=useState([]),[cursor,setCursor]=useState(null),[grid,setGrid]=useState(1),[layer,setLayer]=useState('0'),[command,setCommand]=useState(''),[tab,setTab]=useState('属性'),[name,setName]=useState('新图纸'),[text,setText]=useState('文字'),[textHeight,setTextHeight]=useState(5),[bubbleNumber,setBubbleNumber]=useState(1),[dimensionKind,setDimensionKind]=useState('linear'),[fields,setFields]=useState({dx:10,dy:0,angle:90,scale:1,count:4,offset:5,trimStart:0,trimEnd:.5}),[property,setProperty]=useState(null),[constraintType,setConstraintType]=useState('length'),[constraintValue,setConstraintValue]=useState('100'),[parameterName,setParameterName]=useState('width'),[parameterValue,setParameterValue]=useState('100'),[symbol,setSymbol]=useState('wall'),[symbolWidth,setSymbolWidth]=useState(3000),[symbolHeight,setSymbolHeight]=useState(240),[paper,setPaper]=useState('A4'),[printScale,setPrintScale]=useState('fit'),[printColor,setPrintColor]=useState('original'),[printLayout,setPrintLayout]=useState('Model'),[preview,setPreview]=useState(''),[endA,setEndA]=useState(0),[endB,setEndB]=useState(0),[pointText,setPointText]=useState(''),[recovery,setRecovery]=useState(null),[transition,setTransition]=useState(null),[canWrite,setCanWrite]=useState(null),[libraryDirty,setLibraryDirty]=useState(false),[libraryReset,setLibraryReset]=useState(0),[landscape,setLandscape]=useState(false),[connectionRetry,setConnectionRetry]=useState(0)
  const tokenRef=useRef(token),authSeen=useRef({accountKey,token});tokenRef.current=token
  const accountRequest=(path,options={})=>request(path,{...options,token:()=>typeof tokenRef.current==='function'?tokenRef.current():tokenRef.current})
  const recoveryRef=useRef(null),unsavedRef=useRef(false),epoch=useRef(0),busyRef=useRef(false),svg=useRef(null),pan=useRef(null),root=useRef(null),docRef=useRef(doc),previewRef=useRef('');docRef.current=doc;recoveryRef.current=recovery
  const drawingUnit=({0:'图纸单位',1:'in',2:'ft',4:'mm',5:'cm',6:'m'})[doc?.units]||'图纸单位'
  const properties=doc?.customProperties||{},constraints=properties.constraints||[],parameters=properties.parameters||{},selected=(doc?.entities||[]).filter(e=>selection.includes(e.id)),scale=view.width/900
  const propertyDirty=nativePropertyDirty(doc,property,pointText),writeBlocked=busy||canWrite!==true||!!recovery
  unsavedRef.current=busy||propertyDirty||points.length>0||libraryDirty||!!recovery||!!interaction?.points?.length
  const clearPreview=()=>{if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current='';setPreview('')}
  useEffect(()=>{
    let cancelled=false;epoch.current++;busyRef.current=true;setBusy(true);setDoc(null);setDocuments([]);setSelection([]);setPoints([]);setCursor(null);setPrintLayout('Model');setLayer('0');setError('');setRecovery(null);setTransition(null);setCanWrite(null);setActiveLayout('Model');setInteraction(null);setCrosshair(null);setBox(null);clipboard.current=null;clearPreview()
    if(token)Promise.all([accountRequest('',{token}),accountRequest('/capabilities',{token})]).then(async([listing,capabilities])=>{
      if(cancelled)return
      const items=Array.isArray(listing)?listing:listing.items||[];setDocuments(items);setCanWrite(capabilities.canWrite===true)
      let remembered;try{remembered=sessionStorage.getItem('native-drawing:last-open-id')}catch{/* Storage may be unavailable. */}
      if(items.some(item=>item.id===remembered)){
        const result=await accountRequest(`/${remembered}`,{token})
        if(!cancelled){setDoc(result);setName(result.name);fit(result)}
      }
    }).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled){busyRef.current=false;setBusy(false)}})
    else {busyRef.current=false;setBusy(false)}
    return()=>{cancelled=true;epoch.current++}
  },[accountKey,connectionRetry])
  useEffect(()=>{
    const previous=authSeen.current;authSeen.current={accountKey,token}
    if(previous.accountKey!==accountKey||previous.token===token||!token)return
    const scope=epoch.current
    accountRequest('/capabilities').then(result=>{if(scope===epoch.current)setCanWrite(result.canWrite===true)}).catch(error=>{if(scope===epoch.current)setError(error.message)})
  },[token,accountKey])
  useEffect(()=>{const entity=selected.length===1?structuredClone(selected[0]):null;setProperty(entity);setPointText(entity?.type==='LWPOLYLINE'?nativePolylineText(entity.points):'')},[doc,selection.join(',')])
  useEffect(()=>{if(!active)pan.current=null},[active])
  useEffect(()=>{const warn=e=>{if(unsavedRef.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);if(previewRef.current)URL.revokeObjectURL(previewRef.current)}},[])
  useEffect(clearPreview,[paper,printScale,printColor,printLayout,landscape])
  const act=async(fn,options={})=>{
    if(busyRef.current)return
    busyRef.current=true;setBusy(true);setError('');const scope=epoch.current
    try{
      const result=await fn();if(scope!==epoch.current)return
      if(result?.entities){
        if(result.id!==docRef.current?.id)setSelection([])
        else setSelection(current=>current.filter(id=>result.entities.some(entity=>entity.id===id)))
        setPoints([]);setCursor(null);setPrintLayout(current=>validNativeLayout(result.layouts,current));setLayer(current=>result.layers.some(item=>item.name===current)?current:result.layers.some(item=>item.name==='0')?'0':result.layers[0]?.name||'0')
        docRef.current=result;setDoc(result);setName(result.name);setDocuments(old=>[result,...old.filter(d=>d.id!==result.id)]);clearPreview()
        try{sessionStorage.setItem('native-drawing:last-open-id',result.id)}catch{/* The server save is already durable. */}
      }
      if(options.mutation){recoveryRef.current=null;setRecovery(null)}
      options.onSuccess?.(result);return result
    }catch(e){
      if(scope===epoch.current){
        setError(e.message)
        if(options.mutation&&e.retryable){const pending={fn,options};recoveryRef.current=pending;setRecovery(pending)}
        else options.onFailure?.(e)
        if(e.status===409)showToast('图纸版本有变化，本次修改未覆盖云端版本，请重新读取后核对','error')
      }
    }finally{if(scope===epoch.current){busyRef.current=false;setBusy(false)}}
  }
  const mutation=(fn,options={})=>{if(propertyDirty&&!options.allowDirty){setTransition({label:'执行下一项修改',run:()=>act(fn,{...options,mutation:true}),saveAllowed:false});return Promise.resolve()}if(canWrite!==true){setError('当前账号只有读取权限');return Promise.resolve()}if(recoveryRef.current){setError('请先重试未确认的保存，或重新读取云端图纸');return Promise.resolve()}return act(fn,{...options,mutation:true})}
  const operate=(ops,options={})=>{if(!doc||!ops.length)return Promise.resolve();const requestId=createClientId(),identity=doc.id,revision=docRef.current.revision;return mutation(()=>accountRequest(`/${identity}/operations`,{token,method:'POST',body:{requestId,expectedRevision:revision,operations:ops}}),options)}
  const add=(entities,options)=>operate(entities.map(entity=>({op:'add',entity:{layer,...entity}})),options)
  const metadata=changes=>({op:'metadata',customProperties:{...properties,...changes}})
  const fit=d=>{const drawing=d||doc;setView(drawingBounds([...(drawing?.entities||[]),...(drawing?.renderEntities||[])]))}
  const resetDraft=()=>{setInteraction(null);setPoints([]);setCursor(null);const saved=selected.length===1?structuredClone(selected[0]):null;setProperty(saved);setPointText(saved?.type==='LWPOLYLINE'?nativePolylineText(saved.points):'');setLibraryReset(value=>value+1);setLibraryDirty(false)}
  const guard=(label,run,{drawing=true,library=false}={})=>{
    if(busyRef.current)return
    if(recoveryRef.current){setError('请先处理未确认的保存，避免覆盖草稿');return}
    if(propertyDirty||(drawing&&(points.length||interaction?.points?.length))||(library&&libraryDirty))setTransition({label,run,saveAllowed:['切换选择','切换面板','打开图纸','新建图纸','导入图纸','导出图纸','预览图纸'].includes(label)})
    else { try { return run() } catch (error) { setError(error.message || '操作未完成，请重试') } }
  }
  const selectEntities=ids=>guard('切换选择',()=>setSelection(ids),{drawing:false})
  const open=id=>guard('打开图纸',()=>act(()=>accountRequest(`/${id}`,{token}),{onSuccess:fit}),{library:true})
  const reload=()=>{if(!doc)return;const run=()=>{recoveryRef.current=null;setRecovery(null);act(()=>accountRequest(`/${doc.id}`,{token}),{onSuccess:fit})};if(propertyDirty||points.length||libraryDirty||recovery)setTransition({label:'重新读取云端图纸',run});else run()}
  const create=()=>guard('新建图纸',()=>{const requestId=createClientId(),newName=name.trim()||'新图纸';return mutation(()=>accountRequest('',{token,method:'POST',body:{name:newName,requestId}}),{onSuccess:fit})},{library:true})
  const importFile=file=>{if(!file)return;if(!/\.(dwg|dxf)$/i.test(file.name)||!file.size||file.size>20*1024*1024){setError('请选择非空的 DWG / DXF，大小不超过 20 MiB');return}return guard('导入图纸',()=>{const form=new FormData();form.append('file',file);form.append('requestId',createClientId());return mutation(()=>accountRequest('/import',{token,method:'POST',body:form}),{onSuccess:fit})},{library:true})}
  const remove=()=>selection.length&&guard('删除所选图元',()=>operate([{op:'delete',ids:selection},metadata({constraints:constraints.filter(c=>!c.entities.some(id=>selection.includes(id)))})]).then(result=>{if(result)setSelection([])}))
  const undo=redo=>doc&&guard(redo?'重做':'撤销',()=>{const requestId=createClientId(),identity=doc.id,revision=docRef.current.revision;return mutation(()=>accountRequest(`/${identity}/${redo?'redo':'undo'}`,{token,method:'POST',body:{requestId,expectedRevision:revision}}))},{library:true})
  const chooseTool=t=>{if(busyRef.current||recoveryRef.current)return;return guard('切换工具',()=>{setTool(t);setInteraction(null);setToolGroup(Object.keys(TOOL_GROUPS).find(key=>TOOL_GROUPS[key].tools.includes(t))||'select');setPoints([]);setCursor(null)})}
  const chooseToolGroup=group=>guard('切换工具组',()=>{setToolGroup(group);setTool(TOOL_GROUPS[group].tools.includes(tool)?tool:TOOL_GROUPS[group].initial);setPoints([]);setCursor(null);setTab(group==='transform'?'变换':'属性')},{library:tab==='图库'})
  const saveProperties=()=>{
    try{
      const candidate=property?.type==='LWPOLYLINE'?{...property,points:parseNativePolylineText(pointText)}:property
      if(!candidate)return Promise.resolve()
      const replacements=doc.entities.map(e=>e.id===candidate.id?candidate:e),solved=constraints.length?solveConstraints(replacements,constraints,parameters):replacements
      const ops=solved.filter((e,i)=>JSON.stringify(e)!==JSON.stringify(doc.entities[i])).map(e=>({op:'update',id:e.id,changes:e.type==='DIMENSION'?{text:e.text,toleranceUpper:e.toleranceUpper,toleranceLower:e.toleranceLower,toleranceEnabled:e.toleranceEnabled,style:e.style,layer:e.layer,color:e.color,linetype:e.linetype,lineweight:e.lineweight}:entityChanges(e)}))
      return ops.length?operate(ops,{allowDirty:true}):Promise.resolve(doc)
    }catch(e){setError(e.message);return Promise.resolve()}
  }
  const world=e=>{const point=svg.current.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const matrix=svg.current.getScreenCTM(),p=point.matrixTransform(matrix.inverse());let result=snapEnabled?snapPoint([p.x,-p.y],visibleNativeEntities(doc),8/matrix.a,gridVisible?grid:0):[p.x,-p.y];const anchor=interaction?.points?.at(-1)||points.at(-1);if(anchor&&(orthogonal||polarTracking)){const dx=result[0]-anchor[0],dy=result[1]-anchor[1];if(orthogonal)result=Math.abs(dx)>Math.abs(dy)?[result[0],anchor[1]]:[anchor[0],result[1]];else{const angle=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*Math.PI/4,length=Math.hypot(dx,dy);result=[anchor[0]+length*Math.cos(angle),anchor[1]+length*Math.sin(angle)]}}return result}
  const finishPolyline=()=>{if(points.length>=2)return add([{type:'LWPOLYLINE',points:points.map(p=>[...p,0]),closed:false}])}
  const draw=p=>{
    if(!doc||busyRef.current||recoveryRef.current||!active||activeLayout!=='Model')return
    lastPoint.current=p
    if(interaction){interactionPoint(p);return}
    if(tool!=='select'&&canWrite!==true)return
    if(tool==='select'){selectEntities([]);return}
    if(tool==='pan')return
    if(propertyDirty){setError('请先保存属性或放弃属性修改，再开始绘制');return}
    if(tool==='text'){add([{type:'TEXT',position:[...p,0],text,height:textHeight,rotation:0}]);return}
    if(tool==='bubble'){operate([{op:'bubble',position:p,radius:textHeight,number:bubbleNumber}],{onSuccess:()=>setBubbleNumber(n=>n+1)});return}
    const next=[...points,p];setPoints(next)
    if(tool==='polyline')return
    if(tool==='arc'&&next.length===3){const[c,a,b]=next;add([{type:'ARC',center:[...c,0],radius:Math.hypot(a[0]-c[0],a[1]-c[1]),startAngle:Math.atan2(a[1]-c[1],a[0]-c[0])*180/Math.PI,endAngle:Math.atan2(b[1]-c[1],b[0]-c[0])*180/Math.PI}],{onFailure:()=>setPoints(points)});return}
    if(tool==='ellipse'&&next.length===3){const[c,a,b]=next,major=[a[0]-c[0],a[1]-c[1]],length=Math.hypot(...major),minor=Math.abs((b[0]-c[0])*major[1]-(b[1]-c[1])*major[0])/length;if(length<1e-8||minor<1e-8||minor>length){setError('短半轴须大于零且不超过长半轴');setPoints(points);return}add([{type:'ELLIPSE',center:[...c,0],majorAxis:[...major,0],ratio:minor/length}],{onFailure:()=>setPoints(points)});return}
    if(tool==='dimension'){
      if(next.length===3){try{operate([nativeDimensionDraft({kind:dimensionKind,layer,points:next,entities:visibleNativeEntities(doc),preferredIds:selection})],{onFailure:()=>setPoints(points)})}catch(e){setError(e.message);setPoints(points)}}return
    }
    if(next.length===2){const[a,b]=next;if(tool==='line')add([{type:'LINE',start:[...a,0],end:[...b,0]}],{onFailure:()=>setPoints(points)});if(tool==='circle')add([{type:'CIRCLE',center:[...a,0],radius:Math.hypot(b[0]-a[0],b[1]-a[1])}],{onFailure:()=>setPoints(points)});if(tool==='polygon'){const radius=Math.hypot(b[0]-a[0],b[1]-a[1]),angle=Math.atan2(b[1]-a[1],b[0]-a[0]);add([{type:'LWPOLYLINE',points:Array.from({length:6},(_,i)=>[a[0]+radius*Math.cos(angle+i*Math.PI/3),a[1]+radius*Math.sin(angle+i*Math.PI/3),0]),closed:true}],{onFailure:()=>setPoints(points)})}if(tool==='rectangle')add([{type:'LWPOLYLINE',points:[[a[0],a[1],0],[b[0],a[1],0],[b[0],b[1],0],[a[0],b[1],0]],closed:true}],{onFailure:()=>setPoints(points)})}
  }
  const transform=(kind)=>{
    if(!selection.length)return
    if(['move','rotate','scale','trim'].includes(kind)&&constraints.some(c=>c.entities.some(id=>selection.includes(id)))){setError('所选图元受约束控制，请在约束面板修改尺寸或解除相关约束后变换');return}
    if(kind==='offset')return operate([{op:'offset',ids:selection,distance:fields.offset}])
    if(kind==='trim')return operate(selection.map(id=>({op:'trim',id,start:fields.trimStart,end:fields.trimEnd})))
    const values={translation:kind==='move'||kind==='copy'?[fields.dx,fields.dy]:[0,0],rotation:kind==='rotate'?fields.angle:0,scale:kind==='scale'?fields.scale:1,origin:[0,0],mirror:kind==='mirror'?'y':undefined}
    if(['array','polar'].includes(kind)){if(!Number.isInteger(fields.count)||fields.count<2||fields.count>100){setError('阵列数量须为 2–100');return}const added=[];for(let i=1;i<fields.count;i++)for(const e of selected){if(e.type==='DIMENSION'||!e.editable){setError('阵列请选择基础可编辑图元');return}added.push(transformEntity(e,kind==='array'?{translation:[fields.dx*i,fields.dy*i]}:{rotation:360/fields.count*i}))}return add(added)}
    if(kind==='copy'||kind==='mirror'){if(selected.some(e=>e.type==='DIMENSION'||!e.editable)){setError('复制/镜像请选择基础可编辑图元');return}return add(selected.map(e=>transformEntity(e,values)))}
    return operate([{op:'transform',ids:selection,...values}])
  }
  const solve=(nextConstraints,nextParameters=parameters)=>{
    try{const updated=solveConstraints(doc.entities,nextConstraints,nextParameters),ops=updated.filter((e,i)=>JSON.stringify(e)!==JSON.stringify(doc.entities[i])).map(e=>({op:'update',id:e.id,changes:entityChanges(e)}));operate([...ops,metadata({constraints:nextConstraints,parameters:nextParameters})])}catch(e){setError(e.message)}
  }
  const addConstraint=()=>{if(!selected.length){setError('请先选择约束图元');return}const required=['parallel','perpendicular','coincident','equal','concentric','distance'].includes(constraintType)?2:1;if(selected.length!==required){setError(`该约束需要 ${required} 个图元`);return}solve([...constraints,{id:createClientId(),type:constraintType,entities:selection,value:constraintValue,ends:[endA,endB],...(constraintType==='fixed'?{geometry:structuredClone(selected[0])}:{})}])}
  const log=message=>setCommandLog(items=>[...items.slice(-49),message])
  const showPanel=next=>guard('切换面板',()=>{setTab(next);setInspectorOpen(true)},{drawing:false,library:tab==='图库'})
  const saveNow=()=>{if(propertyDirty)return saveProperties();if(points.length||interaction?.points?.length){setError('请先完成当前绘制或按 Esc 取消');return}showToast(doc?'当前图纸修订已保存':'请先新建或打开图纸')}
  const beginInteraction=kind=>guard('切换工具',()=>{setTool('select');setPoints([]);setInteraction({kind,phase:['measure','paste'].includes(kind)||selection.length?'points':'selection',points:[]});setInspectorOpen(false);log(`${kind==='measure'?'测量':TRANSFORMS[kind]||kind}：${selection.length||['measure','paste'].includes(kind)?'指定第一点':'选择对象后按 Enter'}`)})
  const completeCorner=kind=>{try{if(constraints.some(c=>c.entities.some(id=>selection.includes(id))))throw new Error('所选图元受约束控制，请先解除约束');operate(cadCornerOperations(selected,fields.offset,kind==='chamfer'),{onSuccess:()=>setInteraction(null)})}catch(e){setError(e.message)}}
  const interactionPoint=p=>{
    if(interaction.phase==='selection')return
    const kind=interaction.kind
    if(kind==='fillet'||kind==='chamfer')return
    if(kind==='paste'){if(!clipboard.current?.length){setError('请先复制图元');return}const bounds=drawingBounds(clipboard.current),origin=[bounds.x+bounds.width/1.16*.08,bounds.y+bounds.height/1.16*.08];add(clipboard.current.map(e=>transformEntity(e,{translation:[p[0]-origin[0],p[1]-origin[1]]})),{onSuccess:()=>{setInteraction(null);log('粘贴完成')}});return}
    if(kind==='trim'){try{const target=selected.find(e=>e.type==='LINE');operate(cadTrimOperation(target,visibleNativeEntities(doc),p),{onSuccess:()=>setInteraction(null)})}catch(e){setError(e.message)}return}
    const next=[...interaction.points,p]
    if(next.length<2){setInteraction({...interaction,points:next});return}
    const [a,b]=next
    try{
      if(kind==='measure'){log(`距离 ${fmt(Math.hypot(b[0]-a[0],b[1]-a[1]))} ${drawingUnit}；ΔX ${fmt(b[0]-a[0])}，ΔY ${fmt(b[1]-a[1])}`);setInteraction(null);setCommandExpanded(true);return}
      if(constraints.some(c=>c.entities.some(id=>selection.includes(id)))&&!['copy','mirror'].includes(kind))throw new Error('所选图元受约束控制，请先解除约束或修改约束尺寸')
      if(['copy','mirror'].includes(kind)){if(selected.some(e=>!e.editable||e.type==='DIMENSION'))throw new Error('请选择基础可编辑图元');add(selected.map(e=>kind==='mirror'?cadMirror(e,a,b):transformEntity(e,{translation:[b[0]-a[0],b[1]-a[1]]})),{onSuccess:()=>setInteraction(null)});return}
      if(kind==='stretch'){const ops=selected.map(e=>{if(!['LINE','LWPOLYLINE'].includes(e.type))throw new Error('端点拉伸支持直线和多段线');const points=e.type==='LINE'?[e.start,e.end]:e.points;let nearest=0;for(let i=1;i<points.length;i++)if(Math.hypot(points[i][0]-a[0],points[i][1]-a[1])<Math.hypot(points[nearest][0]-a[0],points[nearest][1]-a[1]))nearest=i;const moved=[points[nearest][0]+b[0]-a[0],points[nearest][1]+b[1]-a[1],points[nearest][2]||0];return {op:'update',id:e.id,changes:e.type==='LINE'?{[nearest?'end':'start']:moved}:{points:points.map((p,i)=>i===nearest?moved:p)}}});operate(ops,{onSuccess:()=>setInteraction(null)});return}
      operate([{op:'transform',ids:selection,...cadTransformValues(kind,a,b)}],{onSuccess:()=>setInteraction(null)})
    }catch(e){setError(e.message)}
  }
  const invoke=id=>{
    if(busyRef.current||recoveryRef.current)return
    if(Object.hasOwn(TOOLS,id)){chooseTool(id);setToolSettings(['text','dimension','bubble'].includes(id));return}
    if(['move','copy','rotate','scale','mirror','stretch','trim','measure','paste'].includes(id)){beginInteraction(id);return}
    if(id==='fillet'||id==='chamfer'){beginInteraction(id);return}
    if(id==='erase'){remove();return}if(id==='fit'){fit();return}if(id==='pan'){chooseTool(tool==='pan'?'select':'pan');return}
    if(id==='import'){root.current?.querySelector('input[type=file]')?.click();return}
    if(id==='export'){exportDoc('dxf');return}if(id==='autoBubbles'){autoBubbles();return}
    if(id==='array'||id==='offset'){setTransformKind(id);showPanel('变换');return}
    if(id==='currentLayer'){if(selected.length!==1){setError('请先选择一个图元');return}setLayer(selected[0].layer);return}
    if(id==='restoreLayers'){operate(doc.layers.filter(l=>!l.visible||l.frozen).map(l=>({op:'layer',name:l.name,visible:true,frozen:false})));return}
    if(id==='ungroup'){const groups=doc.groups?.filter(g=>g.ids.some(id=>selection.includes(id)))||[];if(!groups.length){setError('请先选择组内图元');return}operate(groups.map(g=>({op:'ungroup',name:g.name})));return}
    if(id==='group'){if(selection.length<2){setError('请至少选择两个图元后创建组');return}operate([{op:'group',ids:selection}],{onSuccess:()=>log('已创建图元组')});return}
    if(['horizontal','vertical','parallel','perpendicular','coincident'].includes(id)){setConstraintType(id);showPanel('约束');return}
    showPanel({properties:'属性',layers:'图层',library:'图库',constraints:'约束',print:'出图',settings:'设置',purge:'清理'}[id]||'属性')
  }
  const duplicateIds=()=>{const seen=new Set(),ids=[];for(const e of doc?.entities||[]){if(!e.editable||e.type==='DIMENSION'||e.bubble||doc.groups?.some(g=>g.ids.includes(e.id))||constraints.some(c=>c.entities.includes(e.id)))continue;const key=JSON.stringify(entityChanges(e));if(seen.has(e.type+key))ids.push(e.id);else seen.add(e.type+key)}return ids}
  const selectLayout=next=>guard('切换布局',()=>{setActiveLayout(next);setPrintLayout(next);setInteraction(null);setSelection([]);setInspectorOpen(false)},{library:true})
  const createLayout=()=>{let index=1;while(doc.layouts.includes(`Layout${index}`))index++;const name=`Layout${index}`;guard('新建布局',()=>operate([{op:'layout',name,scale:1}],{onSuccess:()=>{setActiveLayout(name);setPrintLayout(name);setSelection([]);setInteraction(null);setInspectorOpen(false)}}),{library:true})}
  const instruction=interaction?interaction.phase==='selection'?'选择对象，按 Enter 确认':interaction.kind==='fillet'||interaction.kind==='chamfer'?'选择两条相交直线，输入半径或距离后应用':interaction.kind==='paste'?'指定粘贴插入点':interaction.kind==='trim'?'点击所选直线上要去除的部分':interaction.kind==='scale'?'指定基点，再输入缩放比例或指定参考距离（10 单位对应比例 1）':interaction.kind==='rotate'?'指定旋转中心，再输入角度或指定方向（X 正方向为 0°）':interaction.points.length?'指定第二点':'指定第一点':tool==='select'?'选择对象；左→右框选，右→左交叉选择':tool==='polyline'?'指定下一顶点；Enter 完成，Esc 取消':tool==='ellipse'?'依次指定中心、长轴端点、短半轴点':tool==='arc'?'依次指定圆心、起点、终点':tool==='circle'?'指定圆心及圆周点':tool==='dimension'?'指定两个定义点，再放置尺寸':tool==='pan'?'拖动画布平移':'点击画布或输入坐标；Esc 取消'
  const runCommand=()=>{if(!active||busyRef.current||recoveryRef.current)return;try{const input=command.trim();const point=cadCoordinate(input,lastPoint.current);log(`> ${input}`);if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(input)&&interaction?.points?.length===1&&['rotate','scale'].includes(interaction.kind)){const value=Number(input),a=interaction.points[0];if(!Number.isFinite(value)||Math.abs(value)>1e7||interaction.kind==='scale'&&value<=0)throw new Error('请输入有效角度或正比例');const b=interaction.kind==='scale'?[a[0]+value*10,a[1]]:[a[0]+Math.cos(value*Math.PI/180),a[1]+Math.sin(value*Math.PI/180)];interactionPoint(b);setCommand('');return}if(point){draw(point);setCommand('');return}const c=input.toUpperCase();const aliases={L:'line',LINE:'line',REC:'rectangle',RECTANG:'rectangle',C:'circle',CIRCLE:'circle',A:'arc',ARC:'arc',PL:'polyline',PLINE:'polyline',T:'text',TEXT:'text',D:'dimension',DIM:'dimension',B:'bubble',EL:'ellipse',POL:'polygon',M:'move',MOVE:'move',CO:'copy',COPY:'copy',RO:'rotate',ROTATE:'rotate',SC:'scale',MI:'mirror',S:'stretch',TR:'trim',F:'fillet',CHA:'chamfer',O:'offset',AR:'array',DI:'measure',PASTE:'paste'};if(aliases[c])invoke(aliases[c]);else if(c==='E'||c==='ERASE')remove();else if(c==='U'||c==='UNDO')undo(false);else if(c==='REDO')undo(true);else if(c==='Z'||c==='FIT'||c==='ZOOM')fit();else if(c==='LA')showPanel('图层');else if(c==='PLOT')showPanel('出图');else if(!c&&interaction?.phase==='selection'){if(!selection.length)setError('请先选择对象');else setInteraction({...interaction,phase:'points'})}else if(!c&&['fillet','chamfer'].includes(interaction?.kind))completeCorner(interaction.kind);else if(!c&&tool==='polyline')finishPolyline();else setError('未知命令。可使用 L / PL / REC / C / A / M / CO / RO / TR / F / DI / LA / PLOT');setCommand('')}catch(e){setError(e.message)}}
  const exportQuery=format=>new URLSearchParams({format,paper,scale:printScale,color:printColor,layout:printLayout,landscape:String(landscape)})
  const exportDoc=format=>guard('导出图纸',()=>act(()=>accountRequest(`/${doc.id}/export?${exportQuery(format)}`,{token,blob:true}),{onSuccess:blob=>saveNativeBlob(blob,format==='original'?doc.source.filename:`${doc.name}.${format}`)}),{library:true})
  const fullPreview=()=>guard('预览图纸',()=>act(()=>accountRequest(`/${doc.id}/export?${exportQuery('svg')}`,{token,blob:true}),{onSuccess:blob=>{clearPreview();previewRef.current=URL.createObjectURL(blob);setPreview(previewRef.current)}}))
  const autoBubbles=()=>{if(!doc.dimensions.length){setError('没有原生尺寸，请先使用标注工具');return}const used=new Set((doc.bubbles||[]).map(b=>b.number));let next=1;const ops=doc.dimensions.filter(d=>!d.bubbleNumber).map((d,i)=>{while(used.has(next))next++;const number=next++;used.add(number);return {op:'bubble',dimensionId:d.id,position:(d.points?.defpoint||[i*15,0]).slice(0,2).map((n,j)=>n+(j?textHeight*3:0)),radius:textHeight,number}});if(!ops.length){showToast('全部尺寸已有气泡编号');return}operate(ops)}
  const onKey=e=>{if(!active)return;if(e.nativeEvent?.isComposing)return;if(e.key==='Escape'){e.preventDefault();setCommand('');setInteraction(null);setBox(null);setPoints([]);setTool('select');selectEntities([]);root.current?.focus();return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='F7'){e.preventDefault();setGridVisible(v=>!v)}if(e.key==='F3'){e.preventDefault();setSnapEnabled(v=>!v)}if(e.key==='F8'){e.preventDefault();setOrthogonal(v=>!v);setPolarTracking(false)}if(e.key==='F10'){e.preventDefault();setPolarTracking(v=>!v);setOrthogonal(false)}if(e.key==='Enter'&&interaction){e.preventDefault();if(['fillet','chamfer'].includes(interaction.kind))completeCorner(interaction.kind);else if(selection.length)setInteraction({...interaction,phase:'points'})}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='c'){e.preventDefault();if(selected.length){clipboard.current=structuredClone(selected.filter(e=>e.editable&&e.type!=='DIMENSION'));log(`已复制 ${clipboard.current.length} 个图元`)}}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='v'){e.preventDefault();invoke('paste')}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove()}if(e.key==='Enter'&&tool==='polyline')finishPolyline();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();undo(e.shiftKey)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selectEntities(visibleNativeEntities(doc).filter(e=>e.editable&&!doc.layers.find(l=>l.name===e.layer)?.locked).map(e=>e.id))}if(!e.metaKey&&!e.ctrlKey&&!e.altKey&&/^[a-zA-Z0-9@.,<+-]$/.test(e.key)){e.preventDefault();setCommand(value=>value+e.key);root.current?.querySelector('input[aria-label="CAD 命令"]')?.focus()}}
  useEffect(()=>{
    if(!active)return
    const save=e=>{if(!(e.metaKey||e.ctrlKey)||e.key.toLowerCase()!=='s')return;e.preventDefault();e.stopPropagation();if(busyRef.current||recoveryRef.current){showToast('保存仍在处理或等待确认，请查看本页提示');return}if(propertyDirty){if(canWrite!==true){showToast('当前账号只有读取权限','error');return}saveProperties().then(result=>{if(result)showToast('属性已保存')})}else showToast(points.length?'请完成当前绘制后保存':libraryDirty?'请在参数图库中保存参数或重建实例':doc?'当前图纸修订已保存':'请先新建或打开图纸')}
    window.addEventListener('keydown',save)
    return()=>window.removeEventListener('keydown',save)
  },[active,property,pointText,doc,points.length,libraryDirty,canWrite])
  useEffect(()=>{
    const scope=++layoutEpoch.current
    if(layoutUrl.current){URL.revokeObjectURL(layoutUrl.current);layoutUrl.current=''}
    setLayoutPreview('');setLayoutLoading(false)
    if(active&&doc&&activeLayout!=='Model'){
      setLayoutLoading(true)
      accountRequest(`/${doc.id}/export?${new URLSearchParams({format:'svg',layout:activeLayout,paper,scale:printScale,color:printColor,landscape:String(landscape)})}`,{blob:true}).then(blob=>{if(scope!==layoutEpoch.current)return;layoutUrl.current=URL.createObjectURL(blob);setLayoutPreview(layoutUrl.current)}).catch(e=>{if(scope===layoutEpoch.current)setError(e.message)}).finally(()=>{if(scope===layoutEpoch.current)setLayoutLoading(false)})
    }
    return()=>{layoutEpoch.current++;if(layoutUrl.current){URL.revokeObjectURL(layoutUrl.current);layoutUrl.current=''}}
  },[active,doc?.id,doc?.revision,activeLayout,paper,printScale,printColor,landscape])
  if(!token)return <section className="native-workspace n2-workspace"><header className="n2-topbar"><button onClick={onBack} aria-label="返回云管理界面"><JoyNiuBrand editor/></button></header><div className="n2-login"><h1>二维绘图</h1><p>登录后可创建或导入 DWG / DXF，图纸和历史保存在你的账号中。</p><button onClick={onLogin}>登录并开始绘图</button><button onClick={onBack}>返回云管理</button></div></section>
  return <section className="native-workspace n2-workspace" ref={root} tabIndex={0} onKeyDown={onKey} aria-label="原生二维 CAD 工作台">
    <header className="n2-topbar">
      <button className="n2-brand" title="返回云管理界面" aria-label="返回云管理界面" onClick={()=>guard('返回云管理',onBack,{library:true})}><JoyNiuBrand editor/></button>
      <div className="n2-quick-tools"><button title="文件" aria-label="文件" aria-expanded={fileOpen} onClick={()=>setFileOpen(v=>!v)}><NativeCadIcon name="file" size={18}/></button><button aria-label="撤销" title="撤销 Ctrl+Z" disabled={writeBlocked||!doc?.canUndo} onClick={()=>undo(false)}><NativeCadIcon name="undo" size={18}/></button><button aria-label="重做" title="重做 Ctrl+Shift+Z" disabled={writeBlocked||!doc?.canRedo} onClick={()=>undo(true)}><NativeCadIcon name="redo" size={18}/></button><button aria-label="保存" title="保存 Ctrl+S" disabled={writeBlocked||!doc} onClick={saveNow}><NativeCadIcon name="save" size={18}/></button><button aria-label="打印" title="打印" disabled={!doc||busy} onClick={()=>showPanel('出图')}><NativeCadIcon name="print" size={18}/></button></div>
      <span className="n2-top-spacer"/><span className="n2-credit">✦ {creditBalance??'—'}</span><span className={`n2-save-state${busy?' is-saving':''}`} title={doc?`${doc.name} · 修订 ${doc.revision} · ${doc.entities.length} 个实体 · ${busy?'请求处理中':recovery?'保存结果待确认':propertyDirty?'属性未保存':points.length?'绘制尚未完成':'当前修订已保存'}`:''}>{busy?'保存中…':recovery?'待确认':propertyDirty||points.length?'编辑中':'实时保存'}<i/></span><button className="n2-document-title" title="打开图纸与文件管理" onClick={()=>setFileOpen(v=>!v)}>{doc?.name||'未打开图纸'}</button><span className="n2-workspace-type">通用工具栏</span><button aria-label="绘图设置" title="绘图设置" onClick={()=>showPanel('设置')}><NativeCadIcon name="settings" size={18}/></button>
    </header>
    <div className="n2-file-menu" hidden={!fileOpen} aria-label="图纸文件"><header><strong>图纸文件</strong><button aria-label="关闭文件菜单" onClick={()=>setFileOpen(false)}>×</button></header><div className="native-actions"><input aria-label="图纸名称" value={name} onChange={e=>setName(e.target.value)}/><button disabled={writeBlocked} onClick={create}>新建</button>{doc&&<button disabled={writeBlocked} onClick={()=>guard('重命名',()=>operate([{op:'metadata',name}]))}>重命名</button>}<label className="native-file-button">导入 DWG / DXF<input type="file" accept=".dwg,.dxf" disabled={writeBlocked} onChange={e=>{importFile(e.target.files[0]);e.target.value=''}}/></label><select aria-label="打开云图纸" value={doc?.id||''} disabled={busy} onChange={e=>open(e.target.value)}><option value="" disabled>打开云图纸</option>{documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>{doc&&<button disabled={busy} onClick={()=>exportDoc('dxf')}>导出 DXF</button>}</div>{doc&&<p>{doc.name} · 修订 {doc.revision} · {busy?'请求处理中':recovery?'保存结果待确认':propertyDirty?'属性未保存':'当前修订已保存'}</p>}</div>
    {canWrite===false&&<p className="native-note">当前账号为只读，可查看图纸并导出。</p>}
    {error&&<div className="native-error" role="alert"><span>{error}{recovery&&' 草稿已保留。重试同一请求不会重复添加图元或图纸。'}</span><div>{recovery&&<button disabled={busy} onClick={()=>act(recovery.fn,recovery.options)}>重试未确认请求</button>}{doc?<button disabled={busy} onClick={reload}>重新读取</button>:!recovery&&<button disabled={busy} onClick={()=>setConnectionRetry(value=>value+1)}>重新连接</button>}<button disabled={busy} onClick={()=>setError('')}>收起提示</button></div></div>}
    {recovery&&!error&&<p className="native-note"><button disabled={busy} onClick={()=>act(recovery.fn,recovery.options)}>重试未确认请求</button> 草稿仍保留，继续编辑前请确认保存结果。</p>}
    {transition&&<div className="native-draft-dialog" role="dialog" aria-modal="true" aria-label="未保存修改" onKeyDown={event=>nativeDialogKey(event,()=>setTransition(null))}><div><h2>有尚未保存的修改</h2><p>继续{transition.label}会放弃当前本地输入。云端已保存的图纸不受影响。</p><button autoFocus onClick={()=>setTransition(null)}>继续编辑</button>{transition.saveAllowed&&propertyDirty&&!points.length&&!libraryDirty&&!recovery&&<button disabled={busy} onClick={async()=>{const result=await saveProperties();if(result){const next=transition.run;setTransition(null);next()}}}>保存属性后继续</button>}<button disabled={busy} onClick={()=>{const next=transition.run;resetDraft();setTransition(null);next()}}>放弃本地输入并继续</button></div></div>}
    {doc&&<><div className="n2-toolbar">
      {nativeCadRibbon({page:ribbonPage,onPage:setRibbonPage,tool,invoke,disabled:busy||!!recovery,readonly:canWrite!==true||activeLayout!=='Model',layer,layers:doc.layers,onLayer:setLayer,modelSpace:activeLayout==='Model'})}
      {interaction&&<div className="n2-interaction-options"><b>{({move:'移动',copy:'复制',rotate:'旋转',scale:'缩放',mirror:'镜像',stretch:'端点拉伸',trim:'修剪',fillet:'圆角',chamfer:'倒角',paste:'粘贴',measure:'测量'})[interaction.kind]}</b><span>{instruction}</span>{['fillet','chamfer'].includes(interaction.kind)&&<><Numeric label={interaction.kind==='fillet'?'圆角半径':'倒角距离'} value={fields.offset} min={.001} onChange={n=>setFields(f=>({...f,offset:n}))}/><button disabled={writeBlocked||selection.length!==2} onClick={()=>completeCorner(interaction.kind)}>应用</button></>}<button onClick={()=>{setInteraction(null);setPoints([])}}>取消</button></div>}
      <fieldset className="native-tool-settings" disabled={writeBlocked} hidden={!toolSettings||!['text','bubble','dimension'].includes(tool)} aria-label="当前工具设置">
        <div hidden={tool!=='text'}><label>文字内容<input value={text} onChange={e=>setText(e.target.value)}/></label><Numeric label="文字高度" value={textHeight} min={.1} onChange={setTextHeight}/></div>
        <div hidden={tool!=='bubble'}><Numeric label="下一气泡编号" value={bubbleNumber} min={1} step="1" onChange={setBubbleNumber}/><Numeric label="气泡半径" value={textHeight} min={.1} onChange={setTextHeight}/></div>
        <div hidden={tool!=='dimension'}><label>标注类型<select value={dimensionKind} onChange={e=>setDimensionKind(e.target.value)}>{Object.entries({linear:'水平尺寸',aligned:'对齐尺寸',radius:'半径',diameter:'直径',angular:'角度'}).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><span className="native-tool-tip">点选两个定义点，再放置尺寸</span></div>
      </fieldset>
    </div>
    <div className={`native-body n2-body${inspectorOpen?' has-inspector':''}`}><div className="native-canvas-column"><div className="native-canvas" onContextMenu={e=>{e.preventDefault();if(tool==='polyline')finishPolyline();else chooseTool('select')}}>
      <svg ref={svg} viewBox={`${view.x} ${-view.y-view.height} ${view.width} ${view.height}`} preserveAspectRatio="xMidYMid meet" aria-label="二维绘图画布" style={{visibility:activeLayout==='Model'?'visible':'hidden'}} onWheel={e=>{const factor=e.deltaY>0?1.12:.89;setView(v=>({x:v.x+v.width*(1-factor)/2,y:v.y+v.height*(1-factor)/2,width:Math.min(1e7,Math.max(.1,v.width*factor)),height:Math.min(1e7,Math.max(.1,v.height*factor))}))}} onPointerDown={e=>{root.current?.focus();if(e.button===1||e.altKey||tool==='pan'){pan.current={x:e.clientX,y:e.clientY,view};e.currentTarget.setPointerCapture(e.pointerId);return}if(e.button!==0)return;if(tool==='select'&&(!interaction||interaction.phase==='selection'||['fillet','chamfer'].includes(interaction.kind))){const p=world(e);boxStart.current={point:p,x:e.clientX,y:e.clientY,shift:e.shiftKey};e.currentTarget.setPointerCapture(e.pointerId)}else draw(world(e))}} onPointerMove={e=>{const bounds=e.currentTarget.getBoundingClientRect();setCrosshair([e.clientX-bounds.left,e.clientY-bounds.top]);if(boxStart.current){setBox([boxStart.current.point,world(e)]);return}if(pan.current){const m=svg.current.getScreenCTM(),p=pan.current;setView({...p.view,x:p.view.x-(e.clientX-p.x)/m.a,y:p.view.y+(e.clientY-p.y)/m.d});return}setCursor(world(e))}} onPointerUp={e=>{if(boxStart.current){const start=boxStart.current;boxStart.current=null;const b=world(e);if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>4){const ids=cadBoxSelection(visibleNativeEntities(doc),start.point,b);selectEntities(start.shift?[...new Set([...selection,...ids])]:ids)}else if(!interaction)selectEntities([]);setBox(null)}pan.current=null}} onPointerCancel={()=>{pan.current=null;boxStart.current=null;setBox(null)}} onLostPointerCapture={()=>{pan.current=null;boxStart.current=null;setBox(null)}} onPointerLeave={()=>setCrosshair(null)} onDoubleClick={()=>tool==='polyline'&&finishPolyline()}>
        <defs><pattern id="native-grid" width={Math.max(grid,view.width/40)} height={Math.max(grid,view.width/40)} patternUnits="userSpaceOnUse"><path d={`M ${Math.max(grid,view.width/40)} 0 L 0 0 0 ${Math.max(grid,view.width/40)}`} fill="none" stroke="#26303d" strokeWidth={scale*.5}/></pattern></defs><rect x={view.x} y={-view.y-view.height} width={view.width} height={view.height} fill={gridVisible?"url(#native-grid)":"transparent"}/>
        <g transform="scale(1,-1)">{nativeVisibleRenderEntities(doc).map(e=><Entity key={e.id} entity={displayEntity(e,doc.layers)} scale={scale} selected={selection.includes(e.parentId||e.id)} onSelect={event=>{if(event.button===1||event.altKey||tool!=='select'||interaction?.phase==='points'&&!['fillet','chamfer'].includes(interaction.kind))return;event.stopPropagation();root.current?.focus();const id=e.parentId||e.id;const ids=doc.groups?.find(g=>g.ids.includes(id))?.ids||[id];selectEntities(event.shiftKey?(selection.includes(id)?selection.filter(v=>!ids.includes(v)):[...new Set([...selection,...ids])]):ids)}}/>)}{box&&<rect x={Math.min(box[0][0],box[1][0])} y={Math.min(box[0][1],box[1][1])} width={Math.abs(box[1][0]-box[0][0])} height={Math.abs(box[1][1]-box[0][1])} fill={box[1][0]<box[0][0]?'#36b57222':'#4c8aff22'} stroke={box[1][0]<box[0][0]?'#50ca86':'#76aaff'} strokeWidth={scale} strokeDasharray={box[1][0]<box[0][0]?`${scale*4} ${scale*2}`:undefined}/>} {points.length>0&&cursor&&<path d={[...points,cursor].map((p,i)=>`${i?'L':'M'} ${p[0]} ${p[1]}`).join(' ')} stroke="#ffce68" fill="none" strokeDasharray={`${scale*4} ${scale*3}`} strokeWidth={scale}/>} {cursor&&tool!=='select'&&<circle cx={cursor[0]} cy={cursor[1]} r={scale*3} fill="#63d5ff"/>}</g>
      </svg>{activeLayout!=='Model'&&<div className="n2-paper-space">{layoutLoading?<span>正在加载布局…</span>:layoutPreview?<img src={layoutPreview} alt={`${activeLayout} 原生纸空间布局`}/>:<span>布局预览尚未加载</span>}<button onClick={()=>showPanel('出图')}>页面设置与出图</button></div>}
      {crosshair&&activeLayout==='Model'&&<div className="n2-crosshair" style={{left:crosshair[0],top:crosshair[1]}}><i/><b/><span/></div>}
      <div className="n2-ucs" aria-hidden="true"><i/><b/><span>X</span><em>Y</em></div>
      <div hidden={activeLayout!=='Model'} className="n2-view-tools" aria-label="视图导航"><button title="选择" aria-label="选择" onClick={()=>chooseTool('select')}><NativeCadIcon name="select" size={17}/></button><button title="平移" aria-label="平移" onClick={()=>invoke('pan')}><NativeCadIcon name="pan" size={17}/></button><button title="适合窗口" aria-label="适合窗口" onClick={()=>fit()}><NativeCadIcon name="fit" size={17}/></button><button title="放大" aria-label="放大" onClick={()=>setView(v=>({...v,x:v.x+v.width*.1,y:v.y+v.height*.1,width:v.width*.8,height:v.height*.8}))}><NativeCadIcon name="zoom" size={17}/></button><button title="缩小" aria-label="缩小" onClick={()=>setView(v=>({...v,x:v.x-v.width*.125,y:v.y-v.height*.125,width:v.width*1.25,height:v.height*1.25}))}><NativeCadIcon name="zoom" size={17}/></button></div></div>
      <div hidden={activeLayout!=='Model'} className="native-command"><button title="命令记录" aria-label="命令记录" aria-expanded={commandExpanded} onClick={()=>setCommandExpanded(v=>!v)}>⌘</button>{commandExpanded&&<div className="n2-command-history" role="log">{commandLog.length?commandLog.map((line,i)=><div key={i}>{line}</div>):<div>命令就绪。输入命令或坐标，Enter 执行。</div>}</div>}<input aria-label="CAD 命令" placeholder={instruction} value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')runCommand()}}/><button disabled={busy||!!recovery} onClick={runCommand}>执行</button>{tool==='polyline'&&<button disabled={writeBlocked||points.length<2} onClick={finishPolyline}>完成多段线</button>}{points.length>0&&<button disabled={busy||!!recovery} onClick={()=>{setPoints([]);setCursor(null)}}>取消绘制</button>}</div>
      <p className="native-instruction">{tool==='arc'?'依次点选圆心、起点、终点':tool==='dimension'?'依次点选两个定义点及标注位置；半径/直径先点圆心，角度先点顶点':tool==='polyline'?'连续点击顶点，Enter 或右键结束':tool==='circle'?'点选圆心和圆周上的点':tool==='select'?'点击图元后修改属性；全部原始内容可在整图预览中核对':'点击画布绘制，尺寸单位沿用当前图纸'}</p>
      {!!doc.warnings.length&&<p className="native-note">{doc.warnings.join(' ')} {doc.blocks?.length?`${doc.blocks.length} 个块定义保留。`:''}</p>}
      {preview&&<div className="native-preview"><button onClick={clearPreview}>关闭整图预览</button><img alt="原生图纸全实体渲染" src={preview}/></div>}
    </div><aside className="native-inspector" hidden={!inspectorOpen}><header className="n2-inspector-heading"><strong>{tab}</strong><button aria-label="关闭属性面板" onClick={()=>guard('关闭面板',()=>setInspectorOpen(false),{drawing:false,library:tab==='图库'})}>×</button></header><nav>{['属性','变换','约束','图库','图层','出图'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>showPanel(t)}>{t}</button>)}</nav><fieldset className="native-editor-fields" disabled={tab==='出图'?busy:writeBlocked}>
    {tab==='设置'&&<div className="native-form"><h2>绘图设置</h2><Numeric label={`捕捉网格 ${drawingUnit}`} value={grid} min={0} onChange={setGrid}/><label><input type="checkbox" checked={gridVisible} onChange={e=>setGridVisible(e.target.checked)}/>显示网格</label><label><input type="checkbox" checked={snapEnabled} onChange={e=>setSnapEnabled(e.target.checked)}/>对象捕捉</label><label><input type="checkbox" checked={orthogonal} onChange={e=>setOrthogonal(e.target.checked)}/>正交模式</label><p>鼠标中键或 Alt 拖动平移；滚轮缩放；F3 捕捉、F7 网格、F8 正交、F10 极轴。</p></div>}
    {tab==='清理'&&<div className="native-form"><h2>清理重复图元</h2><p>检测完全相同的基础图元。尺寸、约束关联和检验气泡保留。</p><button disabled={writeBlocked||!duplicateIds().length} onClick={()=>operate([{op:'delete',ids:duplicateIds()}])}>删除 {duplicateIds().length} 个重复图元</button><p>清理后可使用撤销恢复。</p></div>}
    {tab==='属性'&&<div className="native-form"><h2>实体属性</h2>
      <label>选择实体<select aria-label="选择图纸实体" value={selection.length===1?selection[0]:''} onChange={e=>selectEntities(e.target.value?[e.target.value]:[])}><option value="">从画布或列表选择</option>{doc.entities.map(e=><option key={e.id} value={e.id}>{e.type} · {e.id} · {e.layer}</option>)}</select></label>
      {property?<><h3>{property.type} · {property.id}</h3>{!property.editable?<p>此实体保留原定义。可在整图预览核对，并导出 DXF。</p>:<>
      {['start','end','center','position'].filter(k=>property[k]).map(k=><div key={k} className="native-pair"><Numeric label={`${{start:'起点',end:'终点',center:'圆心',position:'位置'}[k]} X`} value={property[k][0]} onChange={n=>setProperty(p=>({...p,[k]:[n,p[k][1],p[k][2]||0]}))}/><Numeric label="Y" value={property[k][1]} onChange={n=>setProperty(p=>({...p,[k]:[p[k][0],n,p[k][2]||0]}))}/></div>)}
      {['radius','ratio','height','rotation','startAngle','endAngle'].filter(k=>property[k]!==undefined).map(k=><Numeric key={k} label={{radius:'半径',ratio:'短长轴比',height:'字高',rotation:'转角',startAngle:'起始角',endAngle:'结束角'}[k]} value={property[k]} onChange={n=>setProperty(p=>({...p,[k]:n}))}/>)}
      {property.points&&Array.isArray(property.points)&&<label>轮廓顶点（每行 X,Y,凸度）<textarea rows="6" value={pointText} onChange={e=>setPointText(e.target.value)}/></label>}
      {property.text!==undefined&&<label>文字 / 尺寸覆写<input value={property.text} onChange={e=>setProperty(p=>({...p,text:e.target.value}))}/></label>}
      {property.bubble&&<><Numeric label="检验气泡编号" value={property.bubble.number} min={1} step="1" onChange={n=>setProperty(p=>({...p,bubble:{...p.bubble,number:n}}))}/><button disabled={busy} onClick={()=>{const circle=property.id===property.bubble.circleId?property:doc.entities.find(e=>e.id===property.bubble.circleId);operate([{op:'bubble',dimensionId:property.bubble.dimensionId,number:property.bubble.number,position:circle.center,radius:circle.radius}],{allowDirty:true})}}>更新气泡编号与检验表</button><p>此气泡关联尺寸 {property.bubble.dimensionId}。选择气泡圆可移动整组，选择任一部件删除可移除整组；编号会同步到 Excel。</p></>}{property.type==='DIMENSION'&&<><Numeric label="上偏差" value={property.toleranceUpper} onChange={n=>setProperty(p=>({...p,toleranceUpper:n}))}/><Numeric label="下偏差幅值" value={property.toleranceLower} min={0} onChange={n=>setProperty(p=>({...p,toleranceLower:n}))}/>{['dimtxt','dimasz','dimdec','dimtdec'].map(k=><Numeric key={k} label={{dimtxt:'尺寸字高',dimasz:'箭头大小',dimdec:'小数位',dimtdec:'公差小数位'}[k]} value={property.style?.[k]} onChange={n=>setProperty(p=>({...p,style:{...p.style,[k]:n}}))}/>)}</>}
      <details className="native-settings"><summary>图层与线条样式</summary><div className="native-settings-fields"><label>实体图层<select value={property.layer} onChange={e=>setProperty(p=>({...p,layer:e.target.value}))}>{doc.layers.map(l=><option key={l.name}>{l.name}</option>)}</select></label><label>颜色<select value={property.color} onChange={e=>setProperty(p=>({...p,color:Number(e.target.value)}))}><option value="256">随层</option>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>索引 {n}</option>)}</select></label>
      <label>线型<select value={(property.linetype||'BYLAYER').toUpperCase()} onChange={e=>setProperty(p=>({...p,linetype:e.target.value}))}>{(doc.linetypes||['BYLAYER','CONTINUOUS']).map(n=><option key={n} value={n.toUpperCase()}>{n}</option>)}</select></label><label>线宽 mm<select value={property.lineweight??-1} onChange={e=>setProperty(p=>({...p,lineweight:Number(e.target.value)}))}><option value={-1}>随层</option>{[0,13,18,25,35,50,70,100,140,200].map(n=><option key={n} value={n}>{n/100}</option>)}</select></label></div></details>
      {property.type==='DIMENSION'&&<label><input type="checkbox" checked={property.toleranceEnabled} onChange={e=>setProperty(p=>({...p,toleranceEnabled:e.target.checked}))}/>显示公差</label>}
      {propertyDirty&&<p role="status">属性已修改，点击保存后才写入云端。</p>}<button className="primary" disabled={writeBlocked||!propertyDirty} onClick={saveProperties}>保存属性并求解约束</button></>}</>:<p>点击图元查看属性，Shift 点击可多选。</p>}
    </div>}
    {tab==='变换'&&<div className="native-form"><h2>编辑与变换</h2><label>变换操作<select aria-label="变换操作" value={transformKind} onChange={e=>setTransformKind(e.target.value)}>{Object.entries(TRANSFORMS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>已选 {selection.length} 个图元。{['rotate','mirror','polar','scale'].includes(transformKind)&&'以坐标原点为中心。'}</p>
      {['move','copy','array'].includes(transformKind)&&<div className="native-pair"><Numeric label="位移 X" value={fields.dx} onChange={n=>setFields(f=>({...f,dx:n}))}/><Numeric label="位移 Y" value={fields.dy} onChange={n=>setFields(f=>({...f,dy:n}))}/></div>}
      {['rotate','polar'].includes(transformKind)&&<Numeric label={transformKind==='polar'?'相邻项夹角°':'角度°'} value={fields.angle} onChange={n=>setFields(f=>({...f,angle:n}))}/>}
      {transformKind==='scale'&&<Numeric label="比例" value={fields.scale} min={.001} onChange={n=>setFields(f=>({...f,scale:n}))}/>}
      {['array','polar'].includes(transformKind)&&<Numeric label="阵列总数" value={fields.count} min={2} step="1" onChange={n=>setFields(f=>({...f,count:n}))}/>}
      {transformKind==='offset'&&<Numeric label="偏移距离" value={fields.offset} onChange={n=>setFields(f=>({...f,offset:n}))}/>}
      {transformKind==='trim'&&<div className="native-pair"><Numeric label="裁剪起点 0–1" value={fields.trimStart} onChange={n=>setFields(f=>({...f,trimStart:n}))}/><Numeric label="裁剪终点 0–1" value={fields.trimEnd} onChange={n=>setFields(f=>({...f,trimEnd:n}))}/></div>}
      <button className="primary" disabled={!selection.length||writeBlocked} onClick={()=>{try{transform(transformKind)}catch(e){setError(e.message)}}}>{TRANSFORMS[transformKind]}</button>{!selection.length&&<p>切换「选择」工具，在画布点选图元；Shift 点击可多选。</p>}
    </div>}
    {tab==='约束'&&<div className="native-form"><h2>参数与公式</h2><div className="native-pair"><label>参数名<input value={parameterName} onChange={e=>setParameterName(e.target.value)}/></label><label>值 / 公式<input value={parameterValue} onChange={e=>setParameterValue(e.target.value)}/></label></div><button disabled={busy} onClick={()=>{try{if(!/^[A-Za-z_]\w{0,39}$/.test(parameterName))throw new Error('参数名须用字母/下划线开头');const next={...parameters,[parameterName]:parameterValue};Object.values(next).forEach(v=>evaluateFormula(v,next));solve(constraints,next)}catch(e){setError(e.message)}}}>保存参数并重算</button>
      {Object.entries(parameters).map(([k,v])=><div className="native-record" key={k}><button onClick={()=>{setParameterName(k);setParameterValue(v)}}>{k} = {v}</button><small>{(()=>{try{return fmt(evaluateFormula(v,parameters))}catch{return '公式无效'}})()}</small><button title={`删除参数 ${k}`} onClick={()=>{const next={...parameters};delete next[k];solve(constraints,next)}}>×</button></div>)}
      <h3>几何约束</h3><label>约束类型<select value={constraintType} onChange={e=>setConstraintType(e.target.value)}>{Object.entries(CONSTRAINT_TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>尺寸 / 公式<input value={constraintValue} onChange={e=>setConstraintValue(e.target.value)} placeholder="width / 2"/></label><div className="native-pair"><label>首个图元端点<select value={endA} onChange={e=>setEndA(Number(e.target.value))}><option value={0}>起点/圆心</option><option value={1}>终点</option></select></label><label>第二图元端点<select value={endB} onChange={e=>setEndB(Number(e.target.value))}><option value={0}>起点/圆心</option><option value={1}>终点</option></select></label></div><button className="primary" disabled={busy||!selection.length} onClick={addConstraint}>添加到所选图元</button><p>长度、角度、半径支持参数公式；固定约束保留加入时的几何。冲突时不保存。</p>
      {constraints.map(c=><div className="native-record" key={c.id}><button onClick={()=>selectEntities(c.entities)}>{CONSTRAINT_TYPES[c.type]} · {c.entities.join(',')} {['length','radius','angle','distance'].includes(c.type)?`= ${c.value}`:''}</button><button title="删除约束" onClick={()=>solve(constraints.filter(x=>x.id!==c.id))}>×</button></div>)}
    </div>}
    {tab==='图库'&&<div className="native-form"><h2>专业绘图构件</h2><label>专业 / 构件<select value={symbol} onChange={e=>{const s=PROFESSIONAL_SYMBOLS.find(x=>x.id===e.target.value);setSymbol(s.id);setSymbolWidth(s.width);setSymbolHeight(s.height)}}>{['建筑','给排水','电气','暖通','结构'].map(d=><optgroup key={d} label={d}>{PROFESSIONAL_SYMBOLS.filter(s=>s.discipline===d).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</optgroup>)}</select></label><div className="native-pair"><Numeric label={`宽度 ${drawingUnit}`} value={symbolWidth} min={1} onChange={setSymbolWidth}/><Numeric label={`高度 ${drawingUnit}`} value={symbolHeight} min={1} onChange={setSymbolHeight}/></div><button className="primary" disabled={busy} onClick={()=>{try{add(professionalSymbol(symbol,symbolWidth,symbolHeight,[fields.dx,fields.dy])).then(d=>d&&fit(d))}catch(e){setError(e.message)}}}>按尺寸插入构件</button><p>插入点沿用变换面板 X/Y；构件由可编辑线、圆、弧组成。符号可用于绘图，不附带专业负荷或规范计算。</p>
      <NativeParametricLibrary key={doc.id} document={doc} selected={selected} constraints={constraints} parameters={parameters} translation={[fields.dx,fields.dy]} busy={writeBlocked} onDirtyChange={setLibraryDirty} resetToken={libraryReset} operate={operate} fit={fit} onError={setError}/>

    </div>}
    {tab==='图层'&&<div className="native-form"><h2>图层管理</h2><label>当前 / 新图层名称<input value={layer} onChange={e=>setLayer(e.target.value)}/></label><button disabled={busy} onClick={()=>{if(doc.layers.some(item=>item.name===layer.trim())){setError('图层已存在，请使用下方的图层属性控制');return}operate([{op:'layer',name:layer.trim(),color:7,visible:true}])}}>创建图层</button>{doc.layers.map(l=><div className="native-layer" key={l.name}><label><input type="checkbox" checked={l.visible} disabled={busy} onChange={e=>operate([{op:'layer',name:l.name,visible:e.target.checked}])}/>{l.name}</label><select aria-label={`${l.name} 颜色`} value={l.color} disabled={busy} onChange={e=>operate([{op:'layer',name:l.name,color:Number(e.target.value)}])}>{[1,2,3,4,5,6,7,8,9].map(n=><option key={n}>{n}</option>)}</select><button disabled={busy} onClick={()=>operate([{op:'layer',name:l.name,locked:!l.locked}])}>{l.locked?'解锁':'锁定'}</button></div>)}</div>}
    {tab==='出图'&&<div className="native-form"><h2>打印与检验图</h2><details className="native-settings"><summary>打印设置 · {paper} · {landscape?'横向':'纵向'}</summary><div className="native-settings-fields"><label>打印布局<select value={printLayout} onChange={e=>setPrintLayout(e.target.value)}>{nativeLayouts(doc.layouts).map(l=><option key={l}>{l}</option>)}</select></label><label>纸张方向<select value={landscape?'landscape':'portrait'} onChange={e=>setLandscape(e.target.value==='landscape')}><option value="portrait">纵向</option><option value="landscape">横向</option></select></label><label>纸张<select value={paper} onChange={e=>setPaper(e.target.value)}>{['A4','A3','A2','A1','A0'].map(p=><option key={p}>{p}</option>)}</select></label><label>比例<select value={printScale} onChange={e=>setPrintScale(e.target.value)}>{['fit','1:1','1:2','1:5','1:10','1:20','1:50','1:100'].map(s=><option key={s} value={s}>{s==='fit'?'适合纸张':s}</option>)}</select></label><label>颜色<select value={printColor} onChange={e=>setPrintColor(e.target.value)}><option value="original">原始彩色</option><option value="monochrome">黑白</option></select></label></div></details><button disabled={busy} onClick={fullPreview}>整图预览（含块和原始标注）</button><button disabled={writeBlocked||!doc.dimensions.length} onClick={autoBubbles}>按全部尺寸自动编号气泡</button><p>{doc.dimensions.length} 个原生尺寸；炸开的线和文字不自动冒充尺寸。气泡与检验表编号关联，重复生成只补充未编号尺寸。</p><div className="native-button-grid">{['dxf','dwg','pdf','xlsx','json'].map(f=><button key={f} disabled={busy} onClick={()=>exportDoc(f)}>导出 {f.toUpperCase()}</button>)}</div>{doc.source?.filename&&<button disabled={busy} onClick={()=>exportDoc('original')}>下载上传原文件</button>}<p>纸张、方向、比例和布局用于 PDF / 预览；DXF / DWG 保留整份图纸，Excel 导出模型空间尺寸。</p>{doc.dimensions.map((d,i)=><button className="native-dimension" key={d.id} onClick={()=>{selectEntities([d.id]);setTab('属性')}}><b>{d.bubbleNumber||'待编号'}. {fmt(d.value)}</b><span>{d.kind} · {d.toleranceEnabled?`+${d.toleranceUpper}/−${d.toleranceLower}`:'无公差'}</span></button>)}</div>}
    </fieldset></aside></div>
    <footer className="n2-statusbar"><nav className="n2-layout-tabs" aria-label="模型与布局">{nativeLayouts(doc.layouts).map(layout=><button key={layout} aria-pressed={activeLayout===layout} className={activeLayout===layout?'is-active':''} onClick={()=>selectLayout(layout)}>{layout==='Model'?'模型':layout.replace(/^Layout(\d+)$/,'布局$1')}</button>)}<button aria-label="新建布局" title="新建布局" disabled={writeBlocked} onClick={createLayout}>＋</button></nav><span className="n2-status-spacer"/><label className="n2-scale">比例 <select aria-label="出图比例" value={printScale} onChange={e=>setPrintScale(e.target.value)}>{['fit','1:1','1:2','1:5','1:10','1:20','1:50','1:100'].map(v=><option key={v} value={v}>{v==='fit'?'适合':v}</option>)}</select></label><output title={`图纸坐标 ${drawingUnit}`}>{cursor?cursor.map(fmt).join(', '):'0, 0'}</output><div className="n2-status-tools"><button title="网格 F7" aria-label="网格" aria-pressed={gridVisible} onClick={()=>setGridVisible(v=>!v)}><NativeCadIcon name="grid" size={17}/></button><button title="对象捕捉 F3" aria-label="对象捕捉" aria-pressed={snapEnabled} onClick={()=>setSnapEnabled(v=>!v)}><NativeCadIcon name="snap" size={17}/></button><button title="正交 F8" aria-label="正交" aria-pressed={orthogonal} onClick={()=>{setOrthogonal(v=>!v);setPolarTracking(false)}}><NativeCadIcon name="ortho" size={17}/></button><button title="极轴 F10" aria-label="极轴" aria-pressed={polarTracking} onClick={()=>{setPolarTracking(v=>!v);setOrthogonal(false)}}><NativeCadIcon name="polar" size={17}/></button><button title="特性" aria-label="特性面板" aria-pressed={inspectorOpen} onClick={()=>inspectorOpen?setInspectorOpen(false):showPanel('属性')}><NativeCadIcon name="properties" size={17}/></button><button title="全屏" aria-label="全屏" onClick={()=>document.fullscreenElement?document.exitFullscreen():root.current?.requestFullscreen?.()}><NativeCadIcon name="fit" size={17}/></button></div></footer></>}
    {!doc&&<div className="native-empty"><h2>直接编辑原生图元</h2><p>直线、圆弧、轮廓、文字、尺寸、公差、图层和历史版本。</p><button className="primary" disabled={writeBlocked} onClick={create}>创建第一张图纸</button></div>}
  </section>
}
