import test from 'node:test'
import assert from 'node:assert/strict'
import {evaluateFormula,solveConstraints,transformEntity,snapPoint,professionalSymbol,PROFESSIONAL_SYMBOLS} from './nativeDrawingModel.js'
const line=(id,a,b)=>({id,type:'LINE',start:[...a,0],end:[...b,0]})
test('safe formulas support dependencies and reject loops and code',()=>{assert.equal(evaluateFormula('length / 2 + sqrt(9)',{length:'base * 3',base:20}),33);assert.throws(()=>evaluateFormula('a',{a:'b',b:'a'}),/循环/);assert.throws(()=>evaluateFormula('globalThis.process.exit()'));assert.throws(()=>evaluateFormula('1/0'));assert.throws(()=>evaluateFormula('unknown'));assert.throws(()=>evaluateFormula('1+'));assert.equal(evaluateFormula('sin(pi/2)'),1)})
test('solver preserves fixed datum and meets dimensions across coincident edges',()=>{const a=line('a',[0,0],[10,0]),b=line('b',[10,0],[20,3]);const solved=solveConstraints([a,b],[{type:'fixed',entities:['a'],geometry:a},{type:'coincident',entities:['a','b'],ends:[1,0]},{type:'horizontal',entities:['b']},{type:'length',entities:['b'],value:'width'}],{width:30});assert.ok(Math.abs(solved[1].end[0]-40)<1e-4);assert.ok(Math.abs(solved[1].end[1])<1e-4);assert.deepEqual(a.start,[0,0,0])})
test('contradictory dimensions reject without mutating original entities',()=>{const entities=[line('a',[0,0],[10,0])];assert.throws(()=>solveConstraints(entities,[{type:'length',entities:['a'],value:10},{type:'length',entities:['a'],value:20}]),/冲突/);assert.equal(entities[0].end[0],10)})
test('concentric circles retain positive radii and parameter dependencies',()=>{const entities=[{id:'a',type:'CIRCLE',center:[0,0,0],radius:3},{id:'b',type:'CIRCLE',center:[1,1,0],radius:2}];const out=solveConstraints(entities,[{type:'concentric',entities:['a','b']},{type:'radius',entities:['a'],value:'d/2'},{type:'radius',entities:['b'],value:'d/4'}],{d:20});assert.ok(Math.abs(out[0].center[0]-out[1].center[0])<1e-4);assert.ok(Math.abs(out[0].radius-10)<1e-4);assert.ok(Math.abs(out[1].radius-5)<1e-4)})
test('arc mirror reverses endpoints and polyline bulge without modifying source',()=>{const a={type:'ARC',center:[2,3,0],radius:4,startAngle:10,endAngle:120};const b=transformEntity(a,{mirror:'x'});assert.equal(b.startAngle,-120);assert.equal(b.endAngle,-10);assert.deepEqual(a.center,[2,3,0]);const c=transformEntity({type:'LWPOLYLINE',points:[[1,2,.5],[3,4,0]]},{mirror:'y'});assert.equal(c.points[0][2],-.5)})
test('snapping prioritizes entity points and only falls back to grid',()=>{assert.deepEqual(snapPoint([5.1,.2],[line('a',[0,0],[10,0])],.5,1),[5,0]);assert.deepEqual(snapPoint([12.2,7.8],[],.5,1),[12,8])})
test('all professional components generate finite editable geometry at custom sizes',()=>{for(const s of PROFESSIONAL_SYMBOLS){const entities=professionalSymbol(s.id,s.width*.5,s.height*.5,[10,20]);assert.ok(entities.length>0,s.id);assert.ok(entities.every(e=>['LINE','LWPOLYLINE','CIRCLE','ARC'].includes(e.type)));assert.ok(!JSON.stringify(entities).includes('null'));}assert.throws(()=>professionalSymbol('wall',0,10))})
